' Gambas module file

Public Conn As New Connection ' para acceder desde otros formularios

Public Function conectar() As Connection

  Dim conector As New Connection

  conector.Type = "sqlite"
  conector.Host = User.Home &/ ".gbtexpublisher"
  conector.Name = "db_tex.sqlite"
  Try conector.Open()
  Return conector

  If Error Then
    conector = Null
    Message.Error("Error al conectar con la base de datos. Asegúrese de que el archivo con la base de datos se encuentre disponible. La misma debe encontrarse en " & User.Home &/ ".gbtexpublisher")
  Endif

End

Public Sub desconectar(ByRef conector As Connection)

  conector.Close()
  conector = Null

End
