' Gambas module file

Public Sub CopiarArchivosRevista(rutaTexto As String)

  If Not Exist(File.Dir(rutaTexto) & "/media") Then
    Mkdir File.Dir(rutaTexto) & "/media"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/config") Then
    Mkdir File.Dir(rutaTexto) & "/config"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/art01") Then
    Mkdir File.Dir(rutaTexto) & "/art01"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/tapa") Then
    Mkdir File.Dir(rutaTexto) & "/tapa"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/readme.md") Then
    Copy "./readme.md" To File.Dir(rutaTexto) & "/readme.md"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/LICENSE") Then
    Copy "./LICENSE2" To File.Dir(rutaTexto) & "/LICENSE"
  End If
  'copiamos los archivos de preámbulo de revista
  ' If Not Exist(File.Dir(rutaTexto) & "/files/revista-pdf.tex") Then
  '   Copy "./revista-pdf.tex" To File.Dir(rutaTexto) & "/files/revista-pdf.tex"
  ' End If
  'copiamos los archivos de preámbulo de revista
  ' If Not Exist(File.Dir(rutaTexto) & "/files/revista-xml.tex") Then
  '   Copy "./revista-xml.tex" To File.Dir(rutaTexto) & "/files/revista-xml.tex"
  ' End If
  ' If Not Exist(File.Dir(rutaTexto) & "/files/gbTeXcls.cls") Then
  '   Copy "./gbTeXcls.cls" To File.Dir(rutaTexto) & "/files/gbTeXcls.cls"
  ' End If

End

Public Sub CopiarArchivos(rutaTexto As String)'libros

  If Not Exist(File.Dir(rutaTexto) & "/files") Then
    Mkdir File.Dir(rutaTexto) & "/files"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/correcciones") Then
    Mkdir File.Dir(rutaTexto) & "/correcciones"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/media") Then
    Mkdir File.Dir(rutaTexto) & "/media"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/originales") Then
    Mkdir File.Dir(rutaTexto) & "/originales"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/tapa") Then
    Mkdir File.Dir(rutaTexto) & "/tapa"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/pdf") Then
    Mkdir File.Dir(rutaTexto) & "/pdf"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/artcap") Then
    Mkdir File.Dir(rutaTexto) & "/artcap"
  End If

  'copiamos los archivos de preámbulo de libro
  If Not Exist(File.Dir(rutaTexto) & "/files/book-pdf.tex") Then
    Copy "./book-pdf.tex" To File.Dir(rutaTexto) & "/files/book-pdf.tex"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/files/book-xml.tex") Then
    Copy "./book-xml.tex" To File.Dir(rutaTexto) & "/files/book-xml.tex"
  End If

  'copiamos los archivos de configuracion general
  If Not Exist(File.Dir(rutaTexto) & "/files/imago_custom.css") Then
    Copy "./imago_custom.css" To File.Dir(rutaTexto) & "/files/imago_custom.css"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/files/blitz-lite.css") Then
    Copy "./blitz-lite.css" To File.Dir(rutaTexto) & "/files/blitz-lite.css"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/artcap/inicio-frontmatter.tex") Then
    Copy "./inicio-frontmatter.tex" To File.Dir(rutaTexto) & "/artcap/inicio-frontmatter.tex"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/artcap/agradecimientos.tex") Then
    Copy "./agradecimientos.tex" To File.Dir(rutaTexto) & "/artcap/agradecimientos.tex"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/artcap/colofon.tex") Then
    Copy "./colofon.tex" To File.Dir(rutaTexto) & "/artcap/colofon.tex"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/artcap/indiceautores.tex") Then
    Copy "./indiceautores.tex" To File.Dir(rutaTexto) & "/artcap/indiceautores.tex"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/readme.md") Then
    Copy "./readme.md" To File.Dir(rutaTexto) & "/readme.md"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/LICENSE") Then
    Copy "./LICENSE2" To File.Dir(rutaTexto) & "/LICENSE"
  End If

  If Not Exist(File.Dir(rutaTexto) & "/media/logo-imago-ByW.png") Then
    Copy "./logo-imago-ByW.png" To File.Dir(rutaTexto) & "/media/logo-imago-ByW.png"
  End If

End

Public Sub ManagePdfFolder(rutaTexto As String)

  Dim pdfPath As String = File.Dir(rutaTexto) & "/pdf"

  ' Verifica si la carpeta existe
  If Not Exist(pdfPath) Then
    ' Si no existe, crea la carpeta
    Mkdir pdfPath
  Else
    ' Si existe, borra los archivos con extensión .pdf
    Shell "rm -rf " & pdfPath & "/" & File.BaseName(rutaTexto) & ".pdf" Wait
    Shell "rm -rf " & pdfPath & "/gbTeXdisclaimer-" & File.BaseName(rutaTexto) & ".pdf" Wait
    Shell "rm -rf " & pdfPath & "/_" & File.BaseName(rutaTexto) & ".pdf" Wait
  End If

End Sub

' Función para reemplazar caracteres escapados
Public Sub ReemplazarCaracteresEscapados(rutaTexto As String)

  Dim sFile As String
  Dim contenido As String
  Dim textoModificado As String
  Dim iLoop As Integer
  Dim lineas As String[]

  sFile = File.Dir(rutaTexto) &/ File.BaseName(rutaTexto) & ".tex"

  ' Leer el contenido del archivo, conservando los saltos de línea
  contenido = File.Load(sFile)

  ' Dividir el contenido en líneas usando gb.NewLine
  lineas = Split(contenido, "\n", "", True)

  ' Realizar reemplazos en cada línea
  For iLoop = 0 To lineas.Max
    lineas[iLoop] = Replace(lineas[iLoop], "\\'{a}", "á")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'{e}", "é")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'{i}", "í")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'{o}", "ó")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'{u}", "ú")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'a", "á")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'e", "é")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'i", "í")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'o", "ó")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'u", "ú")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`a", "à")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`e", "è")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`i", "ì")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`o", "ò")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`u", "ù")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^a", "â")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^e", "ê")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^i", "î")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^o", "ô")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^u", "û")
    lineas[iLoop] = Replace(lineas[iLoop], "\\~a", "ã")
    lineas[iLoop] = Replace(lineas[iLoop], "\\~n", "ñ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\~o", "õ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\=a", "ā")
    lineas[iLoop] = Replace(lineas[iLoop], "\\=e", "ē")
    lineas[iLoop] = Replace(lineas[iLoop], "\\=i", "ī")
    lineas[iLoop] = Replace(lineas[iLoop], "\\=o", "ō")
    lineas[iLoop] = Replace(lineas[iLoop], "\\=u", "ū")
    lineas[iLoop] = Replace(lineas[iLoop], "\\c{c}", "ç")
    lineas[iLoop] = Replace(lineas[iLoop], "\\l", "ł")
    lineas[iLoop] = Replace(lineas[iLoop], "\\o", "ø")
    lineas[iLoop] = Replace(lineas[iLoop], "\\v{s}", "š")
    lineas[iLoop] = Replace(lineas[iLoop], "\\v{z}", "ž")
    lineas[iLoop] = Replace(lineas[iLoop], "\\ae", "æ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\AA", "Å")
    lineas[iLoop] = Replace(lineas[iLoop], "\\oe", "œ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\O", "Ø")
    lineas[iLoop] = Replace(lineas[iLoop], "\\AE", "Æ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\ss", "ß")
    lineas[iLoop] = Replace(lineas[iLoop], "\\DH", "Ð")
    lineas[iLoop] = Replace(lineas[iLoop], "\\dh", "ð")
    lineas[iLoop] = Replace(lineas[iLoop], "\\TH", "Þ")
    ' lineas[iLoop] = Replace(lineas[iLoop], "\\th", "þ")'se conflictua con la expresion \thispage
    lineas[iLoop] = Replace(lineas[iLoop], "\\'A", "Á")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'E", "É")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'I", "Í")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'O", "Ó")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'U", "Ú")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`A", "À")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`E", "È")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`I", "Ì")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`O", "Ò")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`U", "Ù")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^A", "Â")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^E", "Ê")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^I", "Î")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^O", "Ô")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^U", "Û")
    lineas[iLoop] = Replace(lineas[iLoop], "\\~A", "Ã")
    lineas[iLoop] = Replace(lineas[iLoop], "\\~N", "Ñ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\~O", "Õ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\=A", "Ā")
    lineas[iLoop] = Replace(lineas[iLoop], "\\=E", "Ē")
    lineas[iLoop] = Replace(lineas[iLoop], "\\=I", "Ī")
    lineas[iLoop] = Replace(lineas[iLoop], "\\=O", "Ō")
    lineas[iLoop] = Replace(lineas[iLoop], "\\=U", "Ū")
    lineas[iLoop] = Replace(lineas[iLoop], "\\c{C}", "Ç")
    lineas[iLoop] = Replace(lineas[iLoop], "\\L", "Ł")
    lineas[iLoop] = Replace(lineas[iLoop], "\\O", "Ø")
    lineas[iLoop] = Replace(lineas[iLoop], "\\v{S}", "Š")
    lineas[iLoop] = Replace(lineas[iLoop], "\\v{Z}", "Ž")
    lineas[iLoop] = Replace(lineas[iLoop], "\\AE", "Æ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\aa", "Å")
    lineas[iLoop] = Replace(lineas[iLoop], "\\OE", "Œ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\o", "Ø")
    lineas[iLoop] = Replace(lineas[iLoop], "\\SS", "ẞ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\DH", "Ð")
    lineas[iLoop] = Replace(lineas[iLoop], "\\TH", "Þ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'{a}", "á")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'{e}", "é")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'{i}", "í")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'{o}", "ó")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'{u}", "ú")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`{a}", "à")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`{e}", "è")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`{i}", "ì")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`{o}", "ò")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`{u}", "ù")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^{a}", "â")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^{e}", "ê")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^{i}", "î")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^{o}", "ô")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^{u}", "û")
    lineas[iLoop] = Replace(lineas[iLoop], "\\~{a}", "ã")
    lineas[iLoop] = Replace(lineas[iLoop], "\\~{n}", "ñ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\~{o}", "õ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\={a}", "ā")
    lineas[iLoop] = Replace(lineas[iLoop], "\\={e}", "ē")
    lineas[iLoop] = Replace(lineas[iLoop], "\\={i}", "ī")
    lineas[iLoop] = Replace(lineas[iLoop], "\\={o}", "ō")
    lineas[iLoop] = Replace(lineas[iLoop], "\\={u}", "ū")
    lineas[iLoop] = Replace(lineas[iLoop], "\\c{c}", "ç")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{l}", "ł")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{o}", "ø")
    lineas[iLoop] = Replace(lineas[iLoop], "\\v{s}", "š")
    lineas[iLoop] = Replace(lineas[iLoop], "\\v{z}", "ž")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{ae}", "æ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{AA}", "Å")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{oe}", "œ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{O}", "Ø")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{AE}", "Æ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{ss}", "ß")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{DH}", "Ð")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{dh}", "ð")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{TH}", "Þ")
    ' lineas[iLoop] = Replace(lineas[iLoop], "\\{th}", "þ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'{A}", "Á")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'{E}", "É")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'{I}", "Í")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'{O}", "Ó")
    lineas[iLoop] = Replace(lineas[iLoop], "\\'{U}", "Ú")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`{A}", "À")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`{E}", "È")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`{I}", "Ì")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`{O}", "Ò")
    lineas[iLoop] = Replace(lineas[iLoop], "\\`{U}", "Ù")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^{A}", "Â")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^{E}", "Ê")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^{I}", "Î")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^{O}", "Ô")
    lineas[iLoop] = Replace(lineas[iLoop], "\\^{U}", "Û")
    lineas[iLoop] = Replace(lineas[iLoop], "\\~{A}", "Ã")
    lineas[iLoop] = Replace(lineas[iLoop], "\\~{N}", "Ñ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\~{O}", "Õ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\={A}", "Ā")
    lineas[iLoop] = Replace(lineas[iLoop], "\\={E}", "Ē")
    lineas[iLoop] = Replace(lineas[iLoop], "\\={I}", "Ī")
    lineas[iLoop] = Replace(lineas[iLoop], "\\={O}", "Ō")
    lineas[iLoop] = Replace(lineas[iLoop], "\\={U}", "Ū")
    lineas[iLoop] = Replace(lineas[iLoop], "\\c{C}", "Ç")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{L}", "Ł")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{O}", "Ø")
    lineas[iLoop] = Replace(lineas[iLoop], "\\v{S}", "Š")
    lineas[iLoop] = Replace(lineas[iLoop], "\\v{Z}", "Ž")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{aa}", "Å")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{OE}", "Œ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{o}", "Ø")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{AE}", "Æ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{SS}", "ẞ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{DH}", "Ð")
    lineas[iLoop] = Replace(lineas[iLoop], "\\{TH}", "Þ")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\'{a}}", "á")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\'{e}}", "é")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\'{i}}", "í")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\'{o}}", "ó")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\'{u}}", "ú")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\`{a}}", "à")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\`{e}}", "è")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\`{i}}", "ì")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\`{o}}", "ò")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\`{u}}", "ù")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\^{a}}", "â")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\^{e}}", "ê")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\^{i}}", "î")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\^{o}}", "ô")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\^{u}}", "û")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\~{a}}", "ã")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\~{n}}", "ñ")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\~{o}}", "õ")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\={a}}", "ā")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\={e}}", "ē")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\={i}}", "ī")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\={o}}", "ō")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\={u}}", "ū")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\c{c}}", "ç")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{l}}", "ł")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{o}}", "ø")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\v{s}}", "š")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\v{z}}", "ž")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{ae}}", "æ")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{AA}}", "Å")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{oe}}", "œ")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{O}}", "Ø")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{AE}}", "Æ")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{ss}}", "ß")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{DH}}", "Ð")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{dh}}", "ð")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{TH}}", "Þ")
    ' lineas[iLoop] = Replace(lineas[iLoop], "{\\{th}}", "þ")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\'{A}}", "Á")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\'{E}}", "É")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\'{I}}", "Í")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\'{O}}", "Ó")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\'{U}}", "Ú")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\`{A}}", "À")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\`{E}}", "È")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\`{I}}", "Ì")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\`{O}}", "Ò")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\`{U}}", "Ù")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\^{A}}", "Â")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\^{E}}", "Ê")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\^{I}}", "Î")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\^{O}}", "Ô")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\^{U}}", "Û")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\~{A}}", "Ã")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\~{N}}", "Ñ")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\~{O}}", "Õ")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\={A}}", "Ā")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\={E}}", "Ē")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\={I}}", "Ī")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\={O}}", "Ō")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\={U}}", "Ū")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\c{C}}", "Ç")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{L}}", "Ł")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{O}}", "Ø")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\v{S}}", "Š")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\v{Z}}", "Ž")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{AE}}", "Æ")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{aa}}", "Å")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{OE}}", "Œ")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{o}}", "Ø")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{SS}}", "ẞ")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{DH}}", "Ð")
    lineas[iLoop] = Replace(lineas[iLoop], "{\\{TH}}", "Þ")
    lineas[iLoop] = Replace(lineas[iLoop], "{ú}", "ú")
    lineas[iLoop] = Replace(lineas[iLoop], "{ù}", "ù")
    lineas[iLoop] = Replace(lineas[iLoop], "{û}", "û")
    lineas[iLoop] = Replace(lineas[iLoop], "{ü}", "ü")
    lineas[iLoop] = Replace(lineas[iLoop], "{ū}", "ū")
    lineas[iLoop] = Replace(lineas[iLoop], "{Ú}", "Ú")
    lineas[iLoop] = Replace(lineas[iLoop], "{Ù}", "Ù")
    lineas[iLoop] = Replace(lineas[iLoop], "{Û}", "Û")
    lineas[iLoop] = Replace(lineas[iLoop], "{Ü}", "Ü")
    lineas[iLoop] = Replace(lineas[iLoop], "{Ū}", "Ū")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textquestiondown", "¿")
    lineas[iLoop] = Replace(lineas[iLoop], "{¿}", "¿")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textexclamdown", "¡")
    lineas[iLoop] = Replace(lineas[iLoop], "{¡}", "¡")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textquotesingle", "'")
  Next

  ' Unir las líneas con gb.NewLine para mantener los saltos de línea
  textoModificado = lineas.Join("\n\n")

  ' Guardar el contenido modificado en el archivo
  File.Save(sFile, textoModificado)

  Message.Info("Reemplazo completado con éxito.")

End Sub

Public Sub menuPuntosSuspensivos(rutaTexto As String)

  Dim sFile As String
  Dim contenido As String
  Dim textoModificado As String
  Dim iLoop As Integer
  Dim lineas As String[]

  sFile = File.Dir(rutaTexto) &/ File.BaseName(rutaTexto) & ".tex"

  ' Leer el contenido del archivo, conservando los saltos de línea
  contenido = File.Load(sFile)

  ' Dividir el contenido en líneas usando gb.NewLine
  lineas = Split(contenido, "\n", "", True)

  ' Realizar reemplazos en cada línea
  For iLoop = 0 To lineas.Max

    lineas[iLoop] = Replace(lineas[iLoop], "{[}\\ldots{]}", "(\\dots)")
    lineas[iLoop] = Replace(lineas[iLoop], "{[}...{]}", "(\\dots)")
    lineas[iLoop] = Replace(lineas[iLoop], "(...)", "(\\dots)")
    lineas[iLoop] = Replace(lineas[iLoop], "[...]", "(\\dots)")
    lineas[iLoop] = Replace(lineas[iLoop], "...", "\\dots")
    lineas[iLoop] = Replace(lineas[iLoop], "\\ldots{}", "\\dots \\ ")
    lineas[iLoop] = Replace(lineas[iLoop], "  ", " ")
    lineas[iLoop] = Replace(lineas[iLoop], "\\ldots", "\\dots")
  Next

  ' Unir las líneas con gb.NewLine para mantener los saltos de línea
  textoModificado = lineas.Join("\n\n")

  ' Guardar el contenido modificado en el archivo
  File.Save(sFile, textoModificado)

  Message.Info("Reemplazo completado con éxito.")

End Sub

Public Sub menuFuncionesVacias(rutaTexto As String)

  Dim sFile As String
  Dim contenido As String
  Dim textoModificado As String
  Dim iLoop As Integer
  Dim lineas As String[]

  sFile = File.Dir(rutaTexto) &/ File.BaseName(rutaTexto) & ".tex"

  ' Leer el contenido del archivo, conservando los saltos de línea
  contenido = File.Load(sFile)

  ' Dividir el contenido en líneas usando gb.NewLine
  lineas = Split(contenido, "\n", "", True)

  ' Realizar reemplazos en cada línea
  For iLoop = 0 To lineas.Max

    lineas[iLoop] = Replace(lineas[iLoop], "\\footnote{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textbf{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textit{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\emph{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textsc{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\footnote{~}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textbf{~}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textit{~}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\emph{~}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\chapter{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\section{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\subsection{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\subsubsection{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\paragraph{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\subparagraph{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\quote{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\begin{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\end{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\hl", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textsuperscript{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\enquote{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textup{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textendash{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textemdash{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textnormal{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textcolor{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\foreignlanguage{}", "")
    lineas[iLoop] = Replace(lineas[iLoop], "\\colorbox{}", "")
  Next

  ' Eliminar líneas en blanco después de \begin{quote}
  For iLoop = lineas.Max - 2 DownTo 0
    If Trim(lineas[iLoop]) = "\begin{quote}" And Trim(lineas[iLoop + 1]) = "" Then
      ' Elimina la línea vacía.
      lineas.Remove(iLoop + 1)
    End If
  Next

  ' Unir las líneas con gb.NewLine para mantener los saltos de línea
  textoModificado = lineas.Join("\n\n")

  ' Guardar el contenido modificado en el archivo
  File.Save(sFile, textoModificado)

  Message.Info("Reemplazo completado con éxito.")

End Sub

Public Sub menuReemplazosOrtograficos(rutaTexto As String)

  Dim sFile As String
  Dim contenido As String
  Dim textoModificado As String
  Dim iLoop As Integer
  Dim lineas As String[]

  sFile = File.Dir(rutaTexto) &/ File.BaseName(rutaTexto) & ".tex"

  ' Leer el contenido del archivo, conservando los saltos de línea
  contenido = File.Load(sFile)

  ' Dividir el contenido en líneas
  lineas = Split(contenido, "\n", "", True)

  ' Realizar reemplazos en cada línea
  For iLoop = 0 To lineas.Max

    lineas[iLoop] = Replace(lineas[iLoop], "\\emph{Ibídem}", "Ibídem")
    lineas[iLoop] = Replace(lineas[iLoop], "\\emph{Ibídem,}", "Ibídem,")
    lineas[iLoop] = Replace(lineas[iLoop], "\\emph{Ibíd}", "Ibíd")
    lineas[iLoop] = Replace(lineas[iLoop], "\\emph{Ibíd,}", "Ibíd,")
    lineas[iLoop] = Replace(lineas[iLoop], "{[}", "[")
    lineas[iLoop] = Replace(lineas[iLoop], "{]}", "]")
    lineas[iLoop] = Replace(lineas[iLoop], "\\emph{: ", ": \\emph{")
    lineas[iLoop] = Replace(lineas[iLoop], "\\emph{, ", ", \\emph{")
    lineas[iLoop] = Replace(lineas[iLoop], "\\emph{; ", "; \\emph{")
    lineas[iLoop] = Replace(lineas[iLoop], "\\emph{. ", ". \\emph{")
    lineas[iLoop] = Replace(lineas[iLoop], "\\emph{ ", " \\emph{")
    lineas[iLoop] = Replace(lineas[iLoop], "---", "--")
    lineas[iLoop] = Replace(lineas[iLoop], "’", "'")
    lineas[iLoop] = Replace(lineas[iLoop], "´", "'")
    lineas[iLoop] = Replace(lineas[iLoop], ",}", "},")
    lineas[iLoop] = Replace(lineas[iLoop], ";}", "};")
    lineas[iLoop] = Replace(lineas[iLoop], "\\footnote{ ", " \\footnote{")
    lineas[iLoop] = Replace(lineas[iLoop], "\\emph{.}", ".")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textbf{.}", ".")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textit{.}", ".")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textsuperscript{.}", ".")
    lineas[iLoop] = Replace(lineas[iLoop], "\\emph{,}", ",")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textbf{,}", ",")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textit{,}", ",")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textsuperscript{,}", ",")
    lineas[iLoop] = Replace(lineas[iLoop], "\\emph{;}", ";")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textbf{;}", ";")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textit{;}", ";")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textsuperscript{;}", ";")
    lineas[iLoop] = Replace(lineas[iLoop], "\\textit{", "\\emph{")
    lineas[iLoop] = Replace(lineas[iLoop], "iglo X", "iglo~X")
    lineas[iLoop] = Replace(lineas[iLoop], "éculo X", "éculo~X")
    lineas[iLoop] = Replace(lineas[iLoop], "\\uline{.}", ".")
  Next

  ' Unir las líneas con doble gb.NewLine para conservar los párrafos
  textoModificado = lineas.Join("\n\n")

  ' Guardar el contenido modificado en el archivo
  File.Save(sFile, textoModificado)

  Message.Info("Reemplazo completado con éxito.")

End Sub

Public Sub GitVersion(raw As String) As String 'Función para chequear si hay versiones nuevas

  Dim s As String
  Dim stx As String[]
  Dim r As String
  Dim v As String

  v = ""
  If Exist("/tmp/project.txt") Then
    Shell "rm /tmp/project.txt" Wait
  Endif

  Shell "wget -O '/tmp/project.txt' '" & raw & "'" Wait
  If Exist("/tmp/project.txt") Then
    s = File.Load("/tmp/project.txt")
    stx = Split(s, "\n")
    For Each r In stx
      If InStr(r, "Version=") Then
        If Split(r, "=")[0] = "Version" Then
          v = Split(r, "=")[1]
          Break
        Endif
      Endif
    Next
  Endif
  Return v

End

'funcion para asegurar metadatos basicos a los archivos
Public Function registrosObligatorios(rutaTexto As String) As Boolean

  Dim campo0, campo1, campo2, campo3, campo4, campo5, campo6, campo7 As String

  campo0 = FMain.txtnombreArchivo.Text
  campo1 = FMain.txt84_bookTitle.Text
  campo2 = FMain.txt05_pdfauthor.Text
  campo3 = FMain.txtDate.Text
  campo4 = FMain.txtSubjet.Text
  campo5 = FMain.txt57_palabrasclave.Text
  campo6 = FMain.txt10_pdfauthortitle.Text
  campo7 = FMain.txtCaptionWriter.Text

  ' Verificar si el campo de metadatos existe
  If campo0 = "" Then
    Message.Error("Debe asegurar la construcción del archivo de metadatos para <strong>" & File.Name(rutaTexto) & "</strong>", "Aceptar")
    FMain.TabPanel1.Index = 3
    Return False
  End If

  ' Verificamos si los otros campos están vacíos
  If campo1 = "" Or campo2 = "" Or campo3 = "" Or campo4 = "" Or campo5 = "" Or campo6 = "" Or campo7 = "" Then
    Message.Error("Uno o más registros de los metadatos obligatorios están vacíos, la operación será cancelada.", "Aceptar")
    FMain.TabPanel1.Index = 3
    Return False
  End If
  ' Si todo está bien, retornamos True
  Return True

End Function

Public Function validarArchivos()

  Dim rutaApp As String
  Dim rutaScriptsExternos As String
  Dim rutaAppR As String

  rutaApp = User.Home &/ ".gbtexpublisher"
  rutaScriptsExternos = rutaApp &/ "ScriptsExternos"
  rutaAppR = User.Home &/ ".respaldogbTeX"

  If Not Exist(rutaApp) Then
    Mkdir rutaApp
  End If

  If Not Exist(rutaScriptsExternos) Then
    Mkdir rutaScriptsExternos
  End If

  If Not Exist(rutaAppR) Then
    Mkdir rutaAppR
  End If

  ' aseguramos que exista el archivo de cabecera para monografias
  If Not Exist(rutaApp &/ "monografia-pdf.tex") Then
    Copy "./monografia-pdf.tex" To rutaApp &/ "monografia-pdf.tex"
  End If

  If Not Exist(rutaApp &/ "db_tex.sqlite") Then
    Copy "./db_tex.sqlite" To rutaApp &/ "db_tex.sqlite"
  End If

  If Not Exist(rutaApp &/ "falta-tapa.png") Then
    Copy "./falta-tapa.png" To rutaApp &/ "falta-tapa.png"
  End If

  If Not Exist(rutaAppR &/ ".gitignore") Then
    Copy "./gitignore_BD" To rutaAppR &/ ".gitignore"
  End If

  If Not Exist(rutaApp & "/gitignore_github") Then
    Copy "./gitignore_github" To rutaApp & "/gitignore_github"
  End If

  If Not Exist(rutaApp & "/gitignore_gitlab") Then
    Copy "./gitignore_gitlab" To rutaApp & "/gitignore_gitlab"
  End If

  'scripts externos
  If Not Exist(rutaScriptsExternos &/ "Contador_global.py") Then
    Copy "./Contador_global.py" To rutaScriptsExternos &/ "Contador_global.py"
  End If

  If Not Exist(rutaScriptsExternos &/ "Control_de_llaves.py") Then
    Copy "./Control_de_llaves.py" To rutaScriptsExternos &/ "Control_de_llaves.py"
  End If

  If Not Exist(rutaScriptsExternos &/ "Control_de_signo_de_admiracion.py") Then
    Copy "./Control_de_signo_de_admiracion.py" To rutaScriptsExternos &/ "Control_de_signo_de_admiracion.py"
  End If

  If Not Exist(rutaScriptsExternos &/ "Control-de_numeros.py") Then
    Copy "./Control-de_numeros.py" To rutaScriptsExternos &/ "Control-de_numeros.py"
  End If

  If Not Exist(rutaScriptsExternos &/ "Control_de_corchetes.py") Then
    Copy "./Control_de_corchetes.py" To rutaScriptsExternos &/ "Control_de_corchetes.py"
  End If

  If Not Exist(rutaScriptsExternos &/ "Control_de_parentesis.py") Then
    Copy "./Control_de_parentesis.py" To rutaScriptsExternos &/ "Control_de_parentesis.py"
  End If

  If Not Exist(rutaScriptsExternos &/ "Control_de_entorno.py") Then
    Copy "./Control_de_entorno.py" To rutaScriptsExternos &/ "Control_de_entorno.py"
  End If

  If Not Exist(rutaScriptsExternos &/ "Control_de_signo_de_pregunta.py") Then
    Copy "./Control_de_signo_de_pregunta.py" To rutaScriptsExternos &/ "Control_de_signo_de_pregunta.py"
  End If

  If Not Exist(rutaScriptsExternos &/ "Reemplazar_endash.py") Then
    Copy "./Reemplazar_endash.py" To rutaScriptsExternos &/ "Reemplazar_endash.py"
  End If

  If Not Exist(rutaScriptsExternos &/ "Buscar_posibles_parencite.py") Then
    Copy "./Buscar_posibles_parencite.py" To rutaScriptsExternos &/ "Buscar_posibles_parencite.py"
  End If

  If Not Exist(rutaScriptsExternos &/ "Limpieza_con_ExpReg.py") Then
    Copy "./Limpieza_con_ExpReg.py" To rutaScriptsExternos &/ "Limpieza_con_ExpReg.py"
  End If

  If Not Exist(rutaScriptsExternos &/ "Reemplazar_comillas.py") Then
    Copy "./Reemplazar_comillas.py" To rutaScriptsExternos &/ "Reemplazar_comillas.py"
  End If

  If Not Exist(rutaScriptsExternos &/ "Controlar_espacio_izquierda.py") Then
    Copy "./Controlar_espacio_izquierda.py" To rutaScriptsExternos &/ "Controlar_espacio_izquierda.py"
  End If

  If Not Exist(rutaApp &/ "Buscar_palabra_Gambas.py") Then
    Copy "./Buscar_palabra_Gambas.py" To rutaApp &/ "Buscar_palabra_Gambas.py"
  End If

End

Public Sub RevisarArchivo()'nos reaseguramos de que el archivo de la base de datos no se haya perdido

  Dim rutaApp As String
  Dim archivo As String

  ' Establecer la ruta y el nombre del archivo
  rutaApp = User.Home &/ ".gbtexpublisher"
  archivo = rutaApp &/ "db_tex.sqlite"

  If Not Exist(rutaApp &/ "db_tex.sqlite") Then
    Message.Error("El archivo <stron>db_tex.sqlite</strong> no se encontró en el directorio: " & rutaApp)
  End If

End

Public Sub ManagePdfFolderMonografia(rutaTexto As String)

  Dim pdfPath As String = File.Dir(rutaTexto) & "/pdf/"

  ' Verifica si la carpeta existe
  If Not Exist(pdfPath) Then
    ' Si no existe, crea la carpeta
    Mkdir pdfPath
  Else
    ' Si existe, borra los archivos con extensión .pdf
    Shell "rm -rf " & pdfPath & File.BaseName(rutaTexto) & ".pdf" Wait
  End If

End Sub

Public Sub Borrar_Aux()

  FMain.TerminalView1.Input("cd " & File.Dir(FMain.TextBox1.Text) & "\n" & "rm *.fuse* odt-*.tex *.bcf-SAVE-ERROR html5-*_html.tex *.bbl-SAVE-ERROR html5-*.tex *.css *.lwarpmkconf *.sidetoc *.conf *.cut *.upa *.upb *.bib.backup *.ndx *.ps *.tex.backup *.bib *.csv *.published *.dat *.txt *.pdf *.bib.sav *.xml *.html *.xhtml *.opf *.xref *.ncx *.tmp *.4ct *.4tc *.4of *.4ot *.4os *.4oy *.4oo *.4og *.lg *.idv *.acn *.acr *.alg *.glg *.gls *.ist *.bak *.log *.aux *.dvi *.lof *.lot *.bit *.idx *.glo *.bbl *.bcf *.ilg *.toc *.ind *.out *.blg *.fdb_latexmk *.fls *.run.xml *.ida *.idn *.inn *.synctex.gz *.xdy *.opf *.epub *.mobi *.ent *.cfg *.lua *.mk4 *.png *.jpg *.svg" & "\n" & "clear" & "\n") 'desde la raiz al directorio padre
  Wait 0.2

  FMain.TerminalView1.SetFocus()

End

Public Sub limpiamosMetadatosLibrosRevistas()

  FMain.txtIdmetadatos.Text = ""
  FMain.txtnombreArchivo.Text = ""
  FMain.txt02_pdfxmp1.Text = ""
  FMain.txt03_pdfxmp2.Text = ""
  FMain.txt04_pdfxmp3.Text = ""
  FMain.txt05_pdfauthor.Text = ""
  FMain.txt06_pdftitle.Text = ""
  FMain.txtSubjet.Text = ""
  FMain.txtKeywords.Text = ""
  FMain.txt09_pdfsubtitle.Text = ""
  FMain.txt10_pdfauthortitle.Text = ""
  FMain.txtDate.Text = ""
  FMain.txtCreationDate.Text = ""
  FMain.txtModDate.Text = ""
  FMain.txtMetaDate.Text = ""
  FMain.txt15_pdfcopyright.Text = ""
  FMain.txt16_pdflicenseurl.Text = ""
  FMain.txtCaptionWriter.Text = ""
  FMain.txtContactAddress.Text = ""
  FMain.txtContactCity.Text = ""
  FMain.txtContactPostCode.Text = ""
  FMain.txtContactCountry.Text = ""
  FMain.txtContactRegion.Text = ""
  FMain.txtContactPhone.Text = ""
  FMain.txtContactEmail.Text = ""
  FMain.txtContactURL.Text = ""
  FMain.txtDocumentId.Text = ""
  FMain.txtPublication.Text = ""
  FMain.txtPublisher.Text = ""
  FMain.cmbType.Text = ""
  FMain.cbPubType.Text = ""
  FMain.txtVolNum.Text = ""
  FMain.txtIssueNum.Text = ""
  FMain.txt33_pdfpagerange.Text = ""
  FMain.txt34_pdfbookedition.Text = ""
  FMain.txt35_pdfisbn.Text = ""
  FMain.txt36_pdfissn.Text = ""
  FMain.txt37_pdfeissn.Text = ""
  FMain.txt38_pdfpubstatus.Text = ""
  FMain.txtLang.Text = ""
  FMain.txt40_pdfmetalang.Text = ""
  FMain.txtBaseURL.Text = ""
  FMain.txt42_pdfurl.Text = ""
  FMain.txt43_pdfdoi.Text = ""
  FMain.cbPDFrendition.Text = ""
  FMain.txtDocumentId.Text = ""
  FMain.cbPDFx.Text = ""
  FMain.txtVersionId.Text = ""
  FMain.txt48_abstract.Text = ""
  FMain.txt49_imagentapa.Text = ""
  FMain.txt50_pagetotal.Text = ""
  FMain.txtCOLECCION.Text = ""
  FMain.txtDirection.Text = ""
  FMain.txt53_traductor.Text = ""
  FMain.txt54_idiomaorig.Text = ""
  FMain.txt55_ilustrador.Text = ""
  FMain.txt56_resumen.Text = ""
  FMain.txt57_palabrasclave.Text = ""
  FMain.txt58_papertitletwo.Text = ""
  FMain.txt59_artrecibido.Text = ""
  FMain.txt60_artaceptado.Text = ""
  FMain.txtFORMATO.Text = ""
  FMain.txt59_opt_source.Text = ""
  FMain.txt82_conferenceVisual.Text = ""
  FMain.txt78_genero.Text = ""
  FMain.txt82_conference.Text = ""
  FMain.txt84_bookTitle.Text = ""
  FMain.txt85_doiRevista.Text = ""
  FMain.txt86_annotation.Text = ""
  FMain.txt87_HTMLFirstPageBottom.Text = ""
  FMain.txt88_audiencia.Text = ""
  FMain.txt89_binding.Text = ""

End

Public Sub VerificarPorcentajeEnTexto(TextoOriginal As String) As String

  Dim i As Integer
  Dim nuevoTexto As String = ""

  ' Recorremos el texto carácter por carácter
  For i = 1 To Len(TextoOriginal)
    ' Si el carácter actual es % y no está precedido por una barra invertida \
    If Mid(TextoOriginal, i, 1) = "%" Then
      If i = 1 Or Mid(TextoOriginal, i - 1, 1) <> "\\" Then
        nuevoTexto &= "\\" ' Adicionar la barra invertida antes del %"
      End If
    End If
    ' Agregar el carácter actual al nuevo texto
    nuevoTexto &= Mid(TextoOriginal, i, 1)
  Next

  ' Devolver el nuevo texto modificado
  Return nuevoTexto

End
