' Gambas module file

Public rutaApp As String = User.Home &/ ".gbtexpublisher"
Public rutaAppR As String = User.Home &/ ".respaldogbTeX"
Public rutaScriptsExternos As String = User.Home &/ ".gbtexpublisher/ScriptsExternos"

Public Sub CopiarArchivos(rutaTexto As String)'libros

  ' usar Exist cuando refiere a directorios y File.RealPath cuando refiere a archivos
  If Not Exist(File.Dir(rutaTexto) & "/files") Then
    Mkdir File.Dir(rutaTexto) & "/files"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/correcciones") Then
    Mkdir File.Dir(rutaTexto) & "/correcciones"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/media") Then
    Mkdir File.Dir(rutaTexto) & "/media"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/originales") Then
    Mkdir File.Dir(rutaTexto) & "/originales"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/tapa") Then
    Mkdir File.Dir(rutaTexto) & "/tapa"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/pdf") Then
    Mkdir File.Dir(rutaTexto) & "/pdf"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/artcap") Then
    Mkdir File.Dir(rutaTexto) & "/artcap"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/docs") Then
    Mkdir File.Dir(rutaTexto) & "/docs"
  End If

  'copiamos los archivos de preámbulo de libro
  If Not File.RealPath(File.Dir(rutaTexto) & "/files/book-pdf.tex") Then
    Copy "./book-pdf.tex" To File.Dir(rutaTexto) & "/files/book-pdf.tex"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/files/book-xml.tex") Then
    Copy "./book-xml.tex" To File.Dir(rutaTexto) & "/files/book-xml.tex"
  End If

  'copiamos los archivos de configuracion general
  If Not File.RealPath(File.Dir(rutaTexto) & "/files/imagoCustom.css") Then
    Copy "./imagoCustom.css" To File.Dir(rutaTexto) & "/files/imagoCustom.css"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/files/imagoEpub.css") Then
    Copy "./imagoEpub.css" To File.Dir(rutaTexto) & "/files/imagoEpub.css"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/artcap/inicio-frontmatter.tex") Then
    Copy "./inicio-frontmatter.tex" To File.Dir(rutaTexto) & "/artcap/inicio-frontmatter.tex"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/artcap/agradecimientos.tex") Then
    Copy "./agradecimientos.tex" To File.Dir(rutaTexto) & "/artcap/agradecimientos.tex"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/artcap/colofon.tex") Then
    Copy "./colofon.tex" To File.Dir(rutaTexto) & "/artcap/colofon.tex"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/artcap/indiceautores.tex") Then
    Copy "./indiceautores.tex" To File.Dir(rutaTexto) & "/artcap/indiceautores.tex"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/readme.md") Then
    Copy "./readme.md" To File.Dir(rutaTexto) & "/readme.md"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/LICENSE") Then
    Copy "./LICENSE2" To File.Dir(rutaTexto) & "/LICENSE"
  End If

  If Not File.RealPath(File.Dir(rutaTexto) & "/media/logo-imago-ByW.png") Then
    Copy "./logo-imago-ByW.png" To File.Dir(rutaTexto) & "/media/logo-imago-ByW.png"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/media/desconocido.png") Then
    Copy "./desconocido.png" To File.Dir(rutaTexto) & "/media/desconocido.png"
  End If

  ' copiamos archivos para página html
  If Not File.RealPath(File.Dir(rutaTexto) & "/docs/logo-imago.png") Then
    Copy "./logo-imago.png" To File.Dir(rutaTexto) & "/docs/logo-imago.png"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/docs/descarga.png") Then
    Copy "./descarga.png" To File.Dir(rutaTexto) & "/docs/descarga.png"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/docs/orcid.png") Then
    Copy "./orcid.png" To File.Dir(rutaTexto) & "/docs/orcid.png"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/docs/imago1.css") Then
    Copy "./imago1.css" To File.Dir(rutaTexto) & "/docs/imago1.css"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/docs/favicon.jpg") Then
    Copy "./favicon.jpg" To File.Dir(rutaTexto) & "/docs/favicon.jpg"
  End If

End

Public Sub ManagePdfFolder(rutaTexto As String)

  Dim pdfPath As String = File.Dir(rutaTexto) & "/pdf"

  ' Verifica si la carpeta existe
  If Not Exist(pdfPath) Then
    ' Si no existe, crea la carpeta
    Mkdir pdfPath
  Else
    ' borramos todos los archivos pdf del proyecto
    Shell "rm -rf " & pdfPath & "/*.pdf" Wait
  End If

End Sub

Public Sub GitVersion(raw As String) As String 'Función para chequear si hay versiones nuevas

  Dim s As String
  Dim stx As String[]
  Dim r As String
  Dim v As String

  v = ""
  If File.RealPath("/tmp/project.txt") Then
    Shell "rm /tmp/project.txt" Wait
  Endif

  Shell "wget -O '/tmp/project.txt' '" & raw & "'" Wait
  If File.RealPath("/tmp/project.txt") Then
    s = File.Load("/tmp/project.txt")
    stx = Split(s, "\n")
    For Each r In stx
      If InStr(r, "Version=") Then
        If Split(r, "=")[0] = "Version" Then
          v = Split(r, "=")[1]
          Break
        Endif
      Endif
    Next
  Endif
  Return v

End

'funcion para asegurar metadatos basicos a los archivos
Public Function registrosObligatorios(rutaTexto As String) As Boolean

  Dim campo0, campo1, campo2, campo3, campo4, campo5, campo6, campo7 As String

  campo0 = FMain.txtnombreArchivo.Text
  campo1 = FMain.txt84_bookTitle.Text
  campo2 = FMain.txt05_pdfauthor.Text
  campo3 = FMain.txtDate.Text
  campo4 = FMain.txtSubjet.Text
  campo5 = FMain.txt57_palabrasclave.Text
  campo6 = FMain.txt10_pdfauthortitle.Text
  campo7 = FMain.txtCaptionWriter.Text

  ' Verificar si el campo de metadatos existe
  If campo0 = "" Then
    Message.Error("Debe asegurar la construcción del archivo de metadatos para <strong>" & File.Name(rutaTexto) & "</strong>", "Aceptar")
    FMain.TabPanel1.Index = 3
    Return False
  End If

  ' Verificamos si los otros campos están vacíos
  If campo1 = "" Or campo2 = "" Or campo3 = "" Or campo4 = "" Or campo5 = "" Or campo6 = "" Or campo7 = "" Then
    Message.Error("Uno o más registros de los metadatos obligatorios están vacíos, la operación será cancelada.", "Aceptar")
    FMain.TabPanel1.Index = 3
    Return False
  End If
  ' Si todo está bien, retornamos True
  Return True

End Function

Public Sub Borrar_Aux()

  FMain.TerminalView1.Input("cd " & File.Dir(FMain.TextBox1.Text) & "\n" & "rm *.xmpi *.*1 *.*2 *.*3 *.eledsec* *.*end *.fuse* odt-*.tex *.bcf-SAVE-ERROR html5-*_html.tex *.bbl-SAVE-ERROR html5-*.tex *.css *.lwarpmkconf *.sidetoc *.conf *.cut *.upa *.upb *.bib.backup *.ndx *.ps *.tex.backup *.bib *.csv *.published *.dat *.txt *.pdf *.bib.sav *.xml *.html *.xhtml *.opf *.xref *.ncx *.tmp *.4ct *.4tc *.4of *.4ot *.4os *.4oy *.4oo *.4og *.lg *.idv *.acn *.acr *.alg *.glg *.gls *.ist *.bak *.log *.aux *.dvi *.lof *.lot *.bit *.idx *.glo *.bbl *.bcf *.ilg *.toc *.ind *.out *.blg *.fdb_latexmk *.fls *.run.xml *.ida *.idn *.inn *.synctex.gz *.xdy *.opf *.epub *.mobi *.ent *.cfg *.lua *.mk4 *.png *.jpg *.svg" & "\n" & "clear" & "\n") 'desde la raiz al directorio padre
  Wait 0.2

  FMain.TerminalView1.SetFocus()

End

Public Sub limpiamosMetadatosLibrosRevistas()

  FMain.txtIdmetadatos.Text = ""
  FMain.txtnombreArchivo.Text = ""
  FMain.txt02_pdfxmp1.Text = ""
  FMain.txt03_pdfxmp2.Text = ""
  FMain.txt04_pdfxmp3.Text = ""
  FMain.txt05_pdfauthor.Text = ""
  FMain.txt06_pdftitle.Text = ""
  FMain.txtSubjet.Text = ""
  FMain.txtpdfsubject_07b.Text = ""
  FMain.txtpdfsubject_07c.Text = ""
  FMain.txtKeywords.Text = ""
  FMain.txt09_pdfsubtitle.Text = ""
  FMain.txt10_pdfauthortitle.Text = ""
  FMain.txtDate.Text = ""
  FMain.txtCreationDate.Text = ""
  FMain.txtModDate.Text = ""
  FMain.txtMetaDate.Text = ""
  FMain.txt15_pdfcopyright.Text = ""
  FMain.txt16_pdflicenseurl.Text = ""
  FMain.txtCaptionWriter.Text = ""
  FMain.txtContactAddress.Text = ""
  FMain.txtContactCity.Text = ""
  FMain.txtContactPostCode.Text = ""
  FMain.txtContactCountry.Text = ""
  FMain.txtContactRegion.Text = ""
  FMain.txtContactPhone.Text = ""
  FMain.txtContactEmail.Text = ""
  FMain.txtContactURL.Text = ""
  FMain.txtDocumentId.Text = ""
  FMain.txtPublication.Text = ""
  FMain.txtPublisher28.Text = ""
  FMain.cmbType.Text = ""
  FMain.cbPubType.Text = ""
  FMain.txtVolNum.Text = ""
  FMain.txtIssueNum.Text = ""
  FMain.txt33_pdfpagerange.Text = ""
  FMain.txt34_pdfbookedition.Text = ""
  FMain.txt35_pdfisbn.Text = ""
  FMain.txt36_pdfissn.Text = ""
  FMain.txt37_pdfeissn.Text = ""
  FMain.txt38_pdfpubstatus.Text = ""
  FMain.txtLang.Text = ""
  FMain.txt40_pdfmetalang.Text = ""
  FMain.txtBaseURL.Text = ""
  FMain.txt42_pdfurl.Text = ""
  FMain.txt43_pdfdoi.Text = ""
  FMain.cbPDFrendition.Text = ""
  FMain.txtDocumentId.Text = ""
  FMain.cbPDFx.Text = ""
  FMain.txtVersionId.Text = ""
  FMain.txt48_abstract.Text = ""
  FMain.txt48b_abstract.Text = ""
  FMain.txt48c_abstract.Text = ""
  FMain.txt49_imagentapa.Text = ""
  FMain.txt50_pagetotal.Text = ""
  FMain.txtCOLECCION.Text = ""
  FMain.txtDirection.Text = ""
  FMain.txt53_traductor.Text = ""
  FMain.txt54_idiomaorig.Text = ""
  FMain.txt55_ilustrador.Text = ""
  FMain.txt56_resumen.Text = ""
  FMain.txt57_palabrasclave.Text = ""
  FMain.txt57b_palabrasclave.Text = ""
  FMain.txt57c_palabrasclave.Text = ""
  FMain.txt58_papertitletwo.Text = ""
  FMain.txt59_artrecibido.Text = ""
  FMain.txt60_artaceptado.Text = ""
  FMain.txtFORMATO.Text = ""
  FMain.txt59_opt_source.Text = ""
  FMain.txt82_conferenceVisual.Text = ""
  FMain.txt78_genero.Text = ""
  FMain.txt82_conference.Text = ""
  FMain.txt84_bookTitle.Text = ""
  FMain.txt85_doiRevista.Text = ""
  FMain.txt86_annotation.Text = ""
  FMain.txt87_HTMLFirstPageBottom.Text = ""
  FMain.txt88_audiencia.Text = ""
  FMain.txt89_binding.Text = ""
  FMain.txt90_eisbn.Text = ""

End

Public Sub VerificarPorcentajeEnTexto(TextoOriginal As String) As String

  Dim nuevoTexto As String

  nuevoTexto = TextoOriginal

  ' hacemos reemplazos de seguridad
  nuevoTexto = Replace(nuevoTexto, "%", "\\%")
  nuevoTexto = Replace(nuevoTexto, "´", "'")
  nuevoTexto = Replace(nuevoTexto, "’", "'")

  ' Devolvemos el texto modificado
  Return nuevoTexto

End

Public Sub AsignarValoresDesdeGridView(GridV As GridView, Row As Integer, Columnas As Integer[], TextBoxes As TextBox[], ComboBoxes As ComboBox[], TextAreas As TextArea[], TextAreasColumnas As Integer[], ComboBoxesColumnas As Integer[])

  Dim Columna As Integer
  Dim Valor As String

  ' Asignar valores a TextBoxes
  For i As Integer = 0 To TextBoxes.Length - 1
    If i < Columnas.Length Then
      Columna = Columnas[i] ' Asignar el índice de la columna
      Valor = GridV[Row, Columna].Text ' Obtener el valor de la celda
      TextBoxes[i].Text = Valor
    End If
  Next

  ' Asignar valores a ComboBoxes
  For i As Integer = 0 To ComboBoxes.Length - 1
    If i < ComboBoxesColumnas.Length Then
      Columna = ComboBoxesColumnas[i] ' Usar el índice específico para TextAreas
      Valor = GridV[Row, Columna].Text ' Obtener el valor de la celda
      ' Forzar la conversión a cadena
      Valor = CStr(Valor)
      ' Asignar el valor al TextArea
      ComboBoxes[i].Text = Valor
    End If
  Next

  ' Asignar valores a TextAreas
  For i As Integer = 0 To TextAreas.Length - 1
    If i < TextAreasColumnas.Length Then
      Columna = TextAreasColumnas[i] ' Usar el índice específico para TextAreas
      Valor = GridV[Row, Columna].Text ' Obtener el valor de la celda
      ' Forzar la conversión a cadena
      Valor = CStr(Valor)
      ' Asignar el valor al TextArea
      TextAreas[i].Text = Valor
    End If
  Next

End

' Función para configurar las columnas del GridView
Public Sub Configurar_Columnas(grid As GridView)

  grid.Columns.Count = 112
  grid.Header = True
  grid.Columns[0].Title = "ID"
  grid.Columns[0].Width = 0
  grid.Columns[1].Title = ""
  grid.Columns[1].Width = 0
  grid.Columns[2].Title = ""
  grid.Columns[2].Width = 0
  grid.Columns[3].Title = ""
  grid.Columns[3].Width = 0
  grid.Columns[4].Title = "Autor/a"
  grid.Columns[4].Width = 250
  grid.Columns[5].Title = ""
  grid.Columns[5].Width = 0
  grid.Columns[6].Title = "Editor"
  grid.Columns[6].Width = 250
  grid.Columns[7].Title = ""
  grid.Columns[7].Width = 0
  grid.Columns[8].Title = ""
  grid.Columns[8].Width = 0
  grid.Columns[9].Title = ""
  grid.Columns[9].Width = 0
  grid.Columns[10].Title = ""
  grid.Columns[10].Width = 0
  grid.Columns[11].Title = ""
  grid.Columns[11].Width = 0
  grid.Columns[12].Title = ""
  grid.Columns[12].Width = 0
  grid.Columns[13].Title = ""
  grid.Columns[13].Width = 0
  grid.Columns[14].Title = ""
  grid.Columns[14].Width = 0
  grid.Columns[15].Title = ""
  grid.Columns[15].Width = 0
  grid.Columns[16].Title = ""
  grid.Columns[16].Width = 0
  grid.Columns[17].Title = ""
  grid.Columns[17].Width = 0
  grid.Columns[18].Title = ""
  grid.Columns[18].Width = 0
  grid.Columns[19].Title = ""
  grid.Columns[19].Width = 0
  grid.Columns[20].Title = ""
  grid.Columns[20].Width = 0
  grid.Columns[21].Title = ""
  grid.Columns[21].Width = 0
  grid.Columns[22].Title = ""
  grid.Columns[22].Width = 0
  grid.Columns[23].Title = ""
  grid.Columns[23].Width = 0
  grid.Columns[24].Title = "Título"
  grid.Columns[24].Width = 600
  grid.Columns[25].Title = ""
  grid.Columns[25].Width = 0
  grid.Columns[26].Title = ""
  grid.Columns[26].Width = 0
  grid.Columns[27].Title = ""
  grid.Columns[27].Width = 0
  grid.Columns[28].Title = ""
  grid.Columns[28].Width = 0
  grid.Columns[29].Title = "Revista"
  grid.Columns[29].Width = 200
  grid.Columns[30].Title = ""
  grid.Columns[30].Width = 0
  grid.Columns[31].Title = ""
  grid.Columns[31].Width = 0
  grid.Columns[32].Title = ""
  grid.Columns[32].Width = 0
  grid.Columns[33].Title = ""
  grid.Columns[33].Width = 0
  grid.Columns[34].Title = ""
  grid.Columns[34].Width = 0
  grid.Columns[35].Title = ""
  grid.Columns[35].Width = 0
  grid.Columns[36].Title = ""
  grid.Columns[36].Width = 0
  grid.Columns[37].Title = ""
  grid.Columns[37].Width = 0
  grid.Columns[38].Title = ""
  grid.Columns[38].Width = 0
  grid.Columns[39].Title = ""
  grid.Columns[39].Width = 0
  grid.Columns[40].Title = ""
  grid.Columns[40].Width = 0
  grid.Columns[41].Title = ""
  grid.Columns[41].Width = 0
  grid.Columns[42].Title = ""
  grid.Columns[42].Width = 0
  grid.Columns[43].Title = "Año"
  grid.Columns[43].Width = 70
  grid.Columns[44].Title = "Año-Mes-Día"
  grid.Columns[44].Width = 120
  grid.Columns[45].Title = ""
  grid.Columns[45].Width = 0
  grid.Columns[46].Title = ""
  grid.Columns[46].Width = 0
  grid.Columns[47].Title = ""
  grid.Columns[47].Width = 0
  grid.Columns[48].Title = ""
  grid.Columns[48].Width = 0
  grid.Columns[49].Title = ""
  grid.Columns[49].Width = 0
  grid.Columns[50].Title = ""
  grid.Columns[50].Width = 0
  grid.Columns[51].Title = ""
  grid.Columns[51].Width = 0
  grid.Columns[52].Title = ""
  grid.Columns[52].Width = 0
  grid.Columns[53].Title = "Editorial"
  grid.Columns[53].Width = 200
  grid.Columns[54].Title = ""
  grid.Columns[54].Width = 0
  grid.Columns[55].Title = ""
  grid.Columns[55].Width = 0
  grid.Columns[56].Title = ""
  grid.Columns[56].Width = 0
  grid.Columns[57].Title = ""
  grid.Columns[57].Width = 0
  grid.Columns[58].Title = ""
  grid.Columns[58].Width = 0
  grid.Columns[59].Title = ""
  grid.Columns[59].Width = 0
  grid.Columns[60].Title = ""
  grid.Columns[60].Width = 0
  grid.Columns[61].Title = ""
  grid.Columns[61].Width = 0
  grid.Columns[62].Title = ""
  grid.Columns[62].Width = 0
  grid.Columns[63].Title = ""
  grid.Columns[63].Width = 0
  grid.Columns[64].Title = ""
  grid.Columns[64].Width = 0
  grid.Columns[65].Title = ""
  grid.Columns[65].Width = 0
  grid.Columns[66].Title = ""
  grid.Columns[66].Width = 0
  grid.Columns[67].Title = ""
  grid.Columns[67].Width = 0
  grid.Columns[68].Title = ""
  grid.Columns[68].Width = 0
  grid.Columns[69].Title = ""
  grid.Columns[69].Width = 0
  grid.Columns[70].Title = ""
  grid.Columns[70].Width = 0
  grid.Columns[71].Title = ""
  grid.Columns[71].Width = 0
  grid.Columns[72].Title = ""
  grid.Columns[72].Width = 0
  grid.Columns[73].Title = ""
  grid.Columns[73].Width = 0
  grid.Columns[74].Title = ""
  grid.Columns[74].Width = 0
  grid.Columns[75].Title = ""
  grid.Columns[75].Width = 0
  grid.Columns[76].Title = ""
  grid.Columns[76].Width = 0
  grid.Columns[77].Title = ""
  grid.Columns[77].Width = 0
  grid.Columns[78].Title = ""
  grid.Columns[78].Width = 0
  grid.Columns[79].Title = ""
  grid.Columns[79].Width = 0
  grid.Columns[80].Title = ""
  grid.Columns[80].Width = 0
  grid.Columns[81].Title = ""
  grid.Columns[81].Width = 0
  grid.Columns[82].Title = ""
  grid.Columns[82].Width = 0
  grid.Columns[83].Title = ""
  grid.Columns[83].Width = 0
  grid.Columns[84].Title = ""
  grid.Columns[84].Width = 0
  grid.Columns[85].Title = ""
  grid.Columns[85].Width = 0
  grid.Columns[86].Title = ""
  grid.Columns[86].Width = 0
  grid.Columns[87].Title = ""
  grid.Columns[87].Width = 0
  grid.Columns[88].Title = ""
  grid.Columns[88].Width = 0
  grid.Columns[89].Title = ""
  grid.Columns[89].Width = 0
  grid.Columns[90].Title = ""
  grid.Columns[90].Width = 0
  grid.Columns[91].Title = ""
  grid.Columns[91].Width = 0
  grid.Columns[92].Title = ""
  grid.Columns[92].Width = 0
  grid.Columns[93].Title = ""
  grid.Columns[93].Width = 0
  grid.Columns[94].Title = ""
  grid.Columns[94].Width = 0
  grid.Columns[95].Title = ""
  grid.Columns[95].Width = 0
  grid.Columns[96].Title = ""
  grid.Columns[96].Width = 0
  grid.Columns[97].Title = ""
  grid.Columns[97].Width = 0
  grid.Columns[98].Title = ""
  grid.Columns[98].Width = 0
  grid.Columns[99].Title = ""
  grid.Columns[99].Width = 0
  grid.Columns[100].Title = ""
  grid.Columns[100].Width = 0
  grid.Columns[101].Title = ""
  grid.Columns[101].Width = 0
  grid.Columns[102].Title = ""
  grid.Columns[102].Width = 0
  grid.Columns[103].Title = ""
  grid.Columns[103].Width = 0
  grid.Columns[104].Title = ""
  grid.Columns[104].Width = 0
  grid.Columns[105].Title = ""
  grid.Columns[105].Width = 0
  grid.Columns[106].Title = ""
  grid.Columns[106].Width = 0
  grid.Columns[107].Title = ""
  grid.Columns[107].Width = 0
  grid.Columns[108].Title = ""
  grid.Columns[108].Width = 0
  grid.Columns[109].Title = ""
  grid.Columns[109].Width = 0
  grid.Columns[110].Title = ""
  grid.Columns[110].Width = 0
  grid.Columns[111].Title = ""
  grid.Columns[111].Width = 0

End

' Función para mostrar datos en un GridView
Public Sub Mostrar_ListaBIB(grid As GridView)

  Dim i As Integer
  Dim Contenido As Result

  ' Limpiar el GridView
  grid.Clear()

  ' Configurar las columnas
  Configurar_Columnas(grid)

  ' Ejecutar la consulta SQL
  Contenido = FMain.meConn.Exec("SELECT * FROM bibtex ORDER BY id DESC")

  ' Asignar la cantidad de filas según los datos
  grid.Rows.Count = Contenido.Count

  ' Recorrer el resultado de la consulta y llenar el GridView
  For i = 0 To Contenido.Count - 1
    grid[i, 0].Text = Contenido!id
    grid[i, 1].Text = Contenido!tipoEntrada
    grid[i, 2].Text = Contenido!citationKey
    grid[i, 3].Text = Contenido!keywords
    grid[i, 4].Text = Contenido!author
    grid[i, 5].Text = Contenido!bookAuthor
    grid[i, 6].Text = Contenido!editor
    grid[i, 7].Text = Contenido!editorA
    grid[i, 8].Text = Contenido!editorB
    grid[i, 9].Text = Contenido!editorC
    grid[i, 10].Text = Contenido!afterword
    grid[i, 11].Text = Contenido!commentator
    grid[i, 12].Text = Contenido!translator
    grid[i, 13].Text = Contenido!holder
    grid[i, 14].Text = Contenido!shortAuthor
    grid[i, 15].Text = Contenido!editorType
    grid[i, 16].Text = Contenido!editorAtype
    grid[i, 17].Text = Contenido!editorBtype
    grid[i, 18].Text = Contenido!editorCtype
    grid[i, 19].Text = Contenido!foreword
    grid[i, 20].Text = Contenido!introduction
    grid[i, 21].Text = Contenido!annotator
    grid[i, 22].Text = Contenido!gender
    grid[i, 23].Text = Contenido!nameAddOn
    grid[i, 24].Text = Contenido!title
    grid[i, 25].Text = Contenido!shortTitle
    grid[i, 26].Text = Contenido!indexTitle
    grid[i, 27].Text = Contenido!bookTitle
    grid[i, 28].Text = Contenido!mainTitle
    grid[i, 29].Text = Contenido!journalTitle
    grid[i, 30].Text = Contenido!issueTitle
    grid[i, 31].Text = Contenido!eventTitle
    grid[i, 32].Text = Contenido!reprintTitle
    grid[i, 33].Text = Contenido!series
    grid[i, 34].Text = Contenido!bookTitleAddOn
    grid[i, 35].Text = Contenido!mainTitleAddOn
    grid[i, 36].Text = Contenido!journalTitleAddOn
    grid[i, 37].Text = Contenido!issueTitleAddOn
    grid[i, 38].Text = Contenido!eventTitleAddOn
    grid[i, 39].Text = Contenido!chapter
    grid[i, 40].Text = Contenido!volume
    grid[i, 41].Text = Contenido!edition
    grid[i, 42].Text = Contenido!pubState
    grid[i, 43].Text = Contenido!yearY
    grid[i, 44].Text = Contenido!dateD
    grid[i, 45].Text = Contenido!urlDate
    grid[i, 46].Text = Contenido!volumes
    grid[i, 47].Text = Contenido!part
    grid[i, 48].Text = Contenido!issue
    grid[i, 49].Text = Contenido!eventDate
    grid[i, 50].Text = Contenido!origDate
    grid[i, 51].Text = Contenido!version
    grid[i, 52].Text = Contenido!location
    grid[i, 53].Text = Contenido!publisher
    grid[i, 54].Text = Contenido!institution
    grid[i, 55].Text = Contenido!organization
    grid[i, 56].Text = Contenido!pages
    grid[i, 57].Text = Contenido!pagination
    grid[i, 58].Text = Contenido!hyphenation
    grid[i, 59].Text = Contenido!langId
    grid[i, 60].Text = Contenido!language
    grid[i, 61].Text = Contenido!origLocation
    grid[i, 62].Text = Contenido!origPublisher
    grid[i, 63].Text = Contenido!pageTotal
    grid[i, 64].Text = Contenido!venue
    grid[i, 65].Text = Contenido!bookPagination
    grid[i, 66].Text = Contenido!langIdOpts
    grid[i, 67].Text = Contenido!origLanguage
    grid[i, 68].Text = Contenido!isan
    grid[i, 69].Text = Contenido!isbn
    grid[i, 70].Text = Contenido!ismn
    grid[i, 71].Text = Contenido!isrn
    grid[i, 72].Text = Contenido!issn
    grid[i, 73].Text = Contenido!iswc
    grid[i, 74].Text = Contenido!url
    grid[i, 75].Text = Contenido!doi
    grid[i, 76].Text = Contenido!eid
    grid[i, 77].Text = Contenido!eprinttype
    grid[i, 78].Text = Contenido!eprint
    grid[i, 79].Text = Contenido!entrysubtype
    grid[i, 80].Text = Contenido!label
    grid[i, 81].Text = Contenido!howpublisher
    grid[i, 82].Text = Contenido!addendum
    grid[i, 83].Text = Contenido!shorthand
    grid[i, 84].Text = Contenido!shorthandintro
    grid[i, 85].Text = Contenido!etiquetas
    grid[i, 86].Text = Contenido!options
    grid[i, 87].Text = Contenido!ids
    grid[i, 88].Text = Contenido!related
    grid[i, 89].Text = Contenido!relatedType
    grid[i, 90].Text = Contenido!relatedString
    grid[i, 91].Text = Contenido!entryset
    grid[i, 92].Text = Contenido!crossref
    grid[i, 93].Text = Contenido!xref
    grid[i, 94].Text = Contenido!xdata
    grid[i, 95].Text = Contenido!presort
    grid[i, 96].Text = Contenido!sortkey
    grid[i, 97].Text = Contenido!sortname
    grid[i, 98].Text = Contenido!sortshorthand
    grid[i, 99].Text = Contenido!sorttitle
    grid[i, 100].Text = Contenido!indexsorttitle
    grid[i, 101].Text = Contenido!sortyear
    grid[i, 102].Text = Contenido!file
    grid[i, 103].Text = Contenido!abstract
    grid[i, 104].Text = Contenido!library
    grid[i, 105].Text = Contenido!note
    grid[i, 106].Text = Contenido!annotation
    grid[i, 107].Text = Contenido!number
    grid[i, 108].Text = Contenido!creationdate
    grid[i, 109].Text = Contenido!type
    grid[i, 110].Text = Contenido!titleaddon
    grid[i, 111].Text = Contenido!subtitle
    Contenido.MoveNext
  Next

End

' Función para llenar el GridView con datos
Public Sub Mostrar_ListaBibActual(grid As GridView)

  Dim i As Integer
  Dim Contenido As Result
  Dim nombreArchivo As String = File.BaseName(FMain.TextBox1.Text)
  ' Limpiar el GridView
  grid.Clear()

  ' Configurar las columnas
  Configurar_Columnas(grid)

  ' Ejecutar la consulta SQL
  Contenido = FMain.meConn.Exec("SELECT * FROM bibtex WHERE keywords LIKE '%" & nombreArchivo & "%' ORDER BY id DESC;")'LIKE

  ' Asignar la cantidad de filas según los datos
  grid.Rows.Count = Contenido.Count

  ' Recorrer el resultado de la consulta y llenar el GridView
  For i = 0 To Contenido.Count - 1
    grid[i, 0].Text = Contenido!id
    grid[i, 1].Text = Contenido!tipoEntrada
    grid[i, 2].Text = Contenido!citationKey
    grid[i, 3].Text = Contenido!keywords
    grid[i, 4].Text = Contenido!author
    grid[i, 5].Text = Contenido!bookAuthor
    grid[i, 6].Text = Contenido!editor
    grid[i, 7].Text = Contenido!editorA
    grid[i, 8].Text = Contenido!editorB
    grid[i, 9].Text = Contenido!editorC
    grid[i, 10].Text = Contenido!afterword
    grid[i, 11].Text = Contenido!commentator
    grid[i, 12].Text = Contenido!translator
    grid[i, 13].Text = Contenido!holder
    grid[i, 14].Text = Contenido!shortAuthor
    grid[i, 15].Text = Contenido!editorType
    grid[i, 16].Text = Contenido!editorAtype
    grid[i, 17].Text = Contenido!editorBtype
    grid[i, 18].Text = Contenido!editorCtype
    grid[i, 19].Text = Contenido!foreword
    grid[i, 20].Text = Contenido!introduction
    grid[i, 21].Text = Contenido!annotator
    grid[i, 22].Text = Contenido!gender
    grid[i, 23].Text = Contenido!nameAddOn
    grid[i, 24].Text = Contenido!title
    grid[i, 25].Text = Contenido!shortTitle
    grid[i, 26].Text = Contenido!indexTitle
    grid[i, 27].Text = Contenido!bookTitle
    grid[i, 28].Text = Contenido!mainTitle
    grid[i, 29].Text = Contenido!journalTitle
    grid[i, 30].Text = Contenido!issueTitle
    grid[i, 31].Text = Contenido!eventTitle
    grid[i, 32].Text = Contenido!reprintTitle
    grid[i, 33].Text = Contenido!series
    grid[i, 34].Text = Contenido!bookTitleAddOn
    grid[i, 35].Text = Contenido!mainTitleAddOn
    grid[i, 36].Text = Contenido!journalTitleAddOn
    grid[i, 37].Text = Contenido!issueTitleAddOn
    grid[i, 38].Text = Contenido!eventTitleAddOn
    grid[i, 39].Text = Contenido!chapter
    grid[i, 40].Text = Contenido!volume
    grid[i, 41].Text = Contenido!edition
    grid[i, 42].Text = Contenido!pubState
    grid[i, 43].Text = Contenido!yearY
    grid[i, 44].Text = Contenido!dateD
    grid[i, 45].Text = Contenido!urlDate
    grid[i, 46].Text = Contenido!volumes
    grid[i, 47].Text = Contenido!part
    grid[i, 48].Text = Contenido!issue
    grid[i, 49].Text = Contenido!eventDate
    grid[i, 50].Text = Contenido!origDate
    grid[i, 51].Text = Contenido!version
    grid[i, 52].Text = Contenido!location
    grid[i, 53].Text = Contenido!publisher
    grid[i, 54].Text = Contenido!institution
    grid[i, 55].Text = Contenido!organization
    grid[i, 56].Text = Contenido!pages
    grid[i, 57].Text = Contenido!pagination
    grid[i, 58].Text = Contenido!hyphenation
    grid[i, 59].Text = Contenido!langId
    grid[i, 60].Text = Contenido!language
    grid[i, 61].Text = Contenido!origLocation
    grid[i, 62].Text = Contenido!origPublisher
    grid[i, 63].Text = Contenido!pageTotal
    grid[i, 64].Text = Contenido!venue
    grid[i, 65].Text = Contenido!bookPagination
    grid[i, 66].Text = Contenido!langIdOpts
    grid[i, 67].Text = Contenido!origLanguage
    grid[i, 68].Text = Contenido!isan
    grid[i, 69].Text = Contenido!isbn
    grid[i, 70].Text = Contenido!ismn
    grid[i, 71].Text = Contenido!isrn
    grid[i, 72].Text = Contenido!issn
    grid[i, 73].Text = Contenido!iswc
    grid[i, 74].Text = Contenido!url
    grid[i, 75].Text = Contenido!doi
    grid[i, 76].Text = Contenido!eid
    grid[i, 77].Text = Contenido!eprinttype
    grid[i, 78].Text = Contenido!eprint
    grid[i, 79].Text = Contenido!entrysubtype
    grid[i, 80].Text = Contenido!label
    grid[i, 81].Text = Contenido!howpublisher
    grid[i, 82].Text = Contenido!addendum
    grid[i, 83].Text = Contenido!shorthand
    grid[i, 84].Text = Contenido!shorthandintro
    grid[i, 85].Text = Contenido!etiquetas
    grid[i, 86].Text = Contenido!options
    grid[i, 87].Text = Contenido!ids
    grid[i, 88].Text = Contenido!related
    grid[i, 89].Text = Contenido!relatedType
    grid[i, 90].Text = Contenido!relatedString
    grid[i, 91].Text = Contenido!entryset
    grid[i, 92].Text = Contenido!crossref
    grid[i, 93].Text = Contenido!xref
    grid[i, 94].Text = Contenido!xdata
    grid[i, 95].Text = Contenido!presort
    grid[i, 96].Text = Contenido!sortkey
    grid[i, 97].Text = Contenido!sortname
    grid[i, 98].Text = Contenido!sortshorthand
    grid[i, 99].Text = Contenido!sorttitle
    grid[i, 100].Text = Contenido!indexsorttitle
    grid[i, 101].Text = Contenido!sortyear
    grid[i, 102].Text = Contenido!file
    grid[i, 103].Text = Contenido!abstract
    grid[i, 104].Text = Contenido!library
    grid[i, 105].Text = Contenido!note
    grid[i, 106].Text = Contenido!annotation
    grid[i, 107].Text = Contenido!number
    grid[i, 108].Text = Contenido!creationdate
    grid[i, 109].Text = Contenido!type
    grid[i, 110].Text = Contenido!titleaddon
    grid[i, 111].Text = Contenido!subtitle
    Contenido.MoveNext
  Next

End
