' Gambas module file

Private BaseName As String = File.BaseName(FMain.TextBox1.Text)
Private rutaFILES As String = File.Dir(FMain.TextBox1.Text) & "/files"

Public Sub salidaPDFweb() 'generamos el PDF web del libro

  Dim newFile As String
  Dim rutaFija As String
  Dim newLog As String

  ' exportamos el archivo de separata
  Mod_Exportar.ExportToSeparata(FMain.TextBox1.Text)

  ' Llamamos a la función del módulo para verificar los metadatos obligatorios
  If Not Mod_Funciones.registrosObligatorios(FMain.TextBox1.Text) Then
    ' Si la función retorna False, cancelamos la operación
    Return
  End If

  newFile = "pdf-" & BaseName & ".tex"
  rutaFija = File.Dir(FMain.TextBox1.Text) &/ "files"
  newLog = "gbTeX-" & BaseName & ".log"

  Mod_Funciones.Borrar_Aux
  Wait 0.2

  FMain.TabPanel1.Index = 0

  ' obtenemos la exportación de los archivos bib, glo y metadatos
  Mod_Exportar.Exportar2BibTeX(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2Glosario(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2MetadatosPDF(FMain.TextBox1.Text)
  Wait 0.2

  'revisamos la carpeta pdf y borramos el archivo
  Mod_Funciones.ManagePdfFolder(FMain.TextBox1.Text)

  Dim condicional As String = "\\\\PDFtrue"
  FMain.TerminalView1.Input("echo " & condicional & " >> " & rutaFija & "/book-pdf.tex" & "\n")

  FMain.TerminalView1.Input("cat " & rutaFija & "/book-pdf.tex" & " " & File.Name(FMain.TextBox1.Text) & " > " & newFile & "\n")
  Wait 0.2

  Dim limpiarCondicional As String
  limpiarCondicional = "sed -i '/\\\\PDFtrue/d' " & rutaFija & "/book-pdf.tex" & "\n"
  FMain.TerminalView1.Input(limpiarCondicional)

  Dim compilar As String
  compilar = "latexmk -l -f --interaction=nonstopmode -pdflatex=lualatex -pdflua " & newFile & "\n"
  ' Envía el comando al terminal
  FMain.TerminalView1.Input(compilar)
  Wait 0.2

  ' TerminalView1.Input("lualatex --interaction=nonstopmode " & newFile & "\n")
  ' Wait 0.2

  FMain.TerminalView1.Input("rm -rf " & newFile & "\n")
  Wait 0.2

  FMain.TerminalView1.Input("mv " & File.Dir(FMain.TextBox1.Text) &/ "pdf-" & BaseName & ".pdf" & " " & File.Dir(FMain.TextBox1.Text) &/ "pdf/pdf-" & BaseName & ".pdf" & "\n")
  Wait 0.2

  'copiamos /files el archivo .log
  FMain.TerminalView1.Input("cat pdf-" & BaseName & ".log > " & rutaFILES & "/gbTeX-" & BaseName & ".log" & "\n")
  Wait 0.2

  'eliminamos los archivos auxiliares
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/artcap/*.aux" & "\n")
  Wait 0.2

  'eliminamos los archivos bib y glo
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/files/gbTeXglo-" & File.BaseName(FMain.TextBox1.Text) & ".tex" & "\n")
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/files/gbTeXbib-" & File.BaseName(FMain.TextBox1.Text) & ".bib" & "\n")
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/files/gbTeXmeta-" & File.BaseName(FMain.TextBox1.Text) & ".tex" & "\n")
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/files/gbTeXseparata-" & File.BaseName(FMain.TextBox1.Text) & ".tex" & "\n")
  Wait 0.2

  Mod_Funciones.Borrar_Aux

  FMain.TerminalView1.SetFocus()
  FMain.TerminalView1.Refresh()

End

Public Sub salidaPDFimprenta() 'generamos el PDF imprenta del libro

  Dim newFile As String
  Dim rutaFija As String
  Dim newLog As String

  ' exportamos el archivo de separata
  Mod_Exportar.ExportToSeparata(FMain.TextBox1.Text)

  ' Llamamos a la función del módulo para verificar los metadatos obligatorios
  If Not Mod_Funciones.registrosObligatorios(FMain.TextBox1.Text) Then
    ' Si la función retorna False, cancelamos la operación
    Return
  End If

  newFile = "pdf-" & BaseName & ".tex"
  rutaFija = File.Dir(FMain.TextBox1.Text) &/ "files"
  newLog = "gbTeX-" & BaseName & ".log"

  Mod_Funciones.Borrar_Aux
  Wait 0.2

  FMain.TabPanel1.Index = 0

  ' obtenemos la exportación de los archivos bib, glo y metadatos
  Mod_Exportar.Exportar2BibTeX(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2Glosario(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2MetadatosPDF(FMain.TextBox1.Text)
  Wait 0.2

  'revisamos la carpeta pdf y borramos el archivo
  Mod_Funciones.ManagePdfFolder(FMain.TextBox1.Text)

  Dim condicional As String = "\\\\BNPDFtrue"
  FMain.TerminalView1.Input("echo " & condicional & " >> " & rutaFija & "/book-pdf.tex" & "\n")

  FMain.TerminalView1.Input("cat " & rutaFija & "/book-pdf.tex" & " " & File.Name(FMain.TextBox1.Text) & " > " & newFile & "\n")
  Wait 0.2

  Dim limpiarCondicional As String
  limpiarCondicional = "sed -i '/\\\\BNPDFtrue/d' " & rutaFija & "/book-pdf.tex" & "\n"
  FMain.TerminalView1.Input(limpiarCondicional)

  Dim compilar As String
  compilar = "latexmk -l -f --interaction=nonstopmode -pdflatex=lualatex -pdflua " & newFile & "\n"
  FMain.TerminalView1.Input(compilar)
  Wait 0.2

  FMain.TerminalView1.Input("rm -rf " & newFile & "\n")
  Wait 0.2

  FMain.TerminalView1.Input("mv " & File.Dir(FMain.TextBox1.Text) &/ "pdf-" & BaseName & ".pdf" & " " & File.Dir(FMain.TextBox1.Text) &/ "pdf/pdf-" & BaseName & ".pdf" & "\n")
  Wait 0.2

  'copiamos /files el archivo .log
  FMain.TerminalView1.Input("cat pdf-" & BaseName & ".log > " & rutaFILES & "/gbTeX-" & BaseName & ".log" & "\n")
  Wait 0.2

  'eliminamos los archivos auxiliares
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/artcap/*.aux" & "\n")
  Wait 0.2

  'eliminamos los archivos bib y glo
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/files/gbTeXglo-" & File.BaseName(FMain.TextBox1.Text) & ".tex" & "\n")
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/files/gbTeXbib-" & File.BaseName(FMain.TextBox1.Text) & ".bib" & "\n")
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/files/gbTeXmeta-" & File.BaseName(FMain.TextBox1.Text) & ".tex" & "\n")
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/files/gbTeXseparata-" & File.BaseName(FMain.TextBox1.Text) & ".tex" & "\n")
  Wait 0.2

  Mod_Funciones.Borrar_Aux

  FMain.TerminalView1.SetFocus()
  FMain.TerminalView1.Refresh()

End
