' Gambas module file

Public Function LimpiarCamposPublisher()

  Form_ABM_Publisher.txtID.Clear
  Form_ABM_Publisher.txtPublisher.Clear
  Form_ABM_Publisher.txtJournal.Clear
  Form_ABM_Publisher.txtLocation.Clear

End

Public Sub LimpiarCamposGLO()

  FMain.txtIDglosario.Clear
  FMain.txtCLAVEglo.Clear
  FMain.txtARCHIVO.Clear
  FMain.txtNAME.Clear
  FMain.txtDESCRIPTION.Clear
  FMain.txtFIRST.Clear
  FMain.txtTEXT.Clear
  FMain.txtPLURAL.Clear
  FMain.txtFPLURAL.Clear
  FMain.txtSORT.Clear

End

Public Sub LimpiarCamposBIB()

  FMain.txtIDbibtex.Clear
  FMain.cbType.Text = ""
  FMain.ComboBox1.Text = ""
  FMain.cbLANGUAGE.Text = ""
  FMain.CmbRelatedType.Text = ""
  FMain.cbPUBSTATE.Text = ""
  FMain.cbEDITORTYPE.Text = ""
  FMain.cbEDITORTYPEa.Text = ""
  FMain.cbEDITORTYPEb.Text = ""
  FMain.cbEDITORTYPEc.Text = ""
  FMain.cbLANGUAGEID.Text = ""
  FMain.cbOPTIONS.Text = ""
  FMain.txtLANGUAGE.Text = ""
  FMain.txtORIGLANGUAGE.Text = ""
  FMain.txtPAGINATION.Text = ""
  FMain.txtEPRINTYPE.Text = ""
  FMain.txtBookPagination.Text = ""
  FMain.txtKEYWORDS.Text = ""
  FMain.txtJournalYear.Text = ""
  FMain.txtISSUE.Clear
  FMain.txtETIQ.Clear
  FMain.txtCROSSREF.Clear
  FMain.txtCLAVEbib.Clear
  FMain.txtTITLE.Clear
  FMain.txtRELATED.Clear
  FMain.txtYEAR.Clear
  FMain.txtDATEY.Clear
  FMain.txtPUBLISHER.Clear
  FMain.txtLOCATION.Clear
  FMain.txtEDITOR.Clear
  FMain.txtSERIES.Clear
  FMain.txtRELATEDSTRING.Clear
  FMain.txtMAINTITLE.Clear
  FMain.txtLABEL.Clear
  FMain.txtSHORTTITLE.Clear
  FMain.txtEDITION.Clear
  FMain.txtBOOKAUTHOR.Clear
  FMain.txtBOOKTITLE.Clear
  FMain.txtVOLUME.Clear
  FMain.txtNUMBER.Clear
  FMain.txtPAGES.Clear
  FMain.txtJOURNALTITLE.Clear
  FMain.txtURLDATE.Clear
  FMain.txtDOI.Clear
  FMain.txtPART.Clear
  FMain.txtBOLUMES.Clear
  FMain.txtPAGETOTAL.Clear
  FMain.txtISBN.Clear
  FMain.txtISSN.Clear
  FMain.txtORGANIZATION.Clear
  FMain.txtINSTITUTION.Clear
  FMain.txtEVENTTITLE.Clear
  FMain.txtEVENTDATE.Clear
  FMain.txtINTRODUCTION.Clear
  FMain.txtTRANSLATOR.Clear
  FMain.txtAFTERWORD.Clear
  FMain.txtFOREWORD.Clear
  FMain.txtLIBRARY.Clear
  FMain.txtANNOTATION.Clear
  FMain.txtURL.Clear
  FMain.txtCOMMENTATOR.Clear
  FMain.txtANNOTATOR.Clear
  FMain.txtNAMEADDON.Clear
  FMain.txtAUTHOR.Clear
  FMain.txtEDITORa.Clear
  FMain.txtEDITORb.Clear
  FMain.txtEDITORc.Clear
  FMain.txtHOLDER.Clear
  FMain.txtShortAuthor.Clear
  FMain.txtBookTitleAddOn.Clear
  FMain.txtMainTitleAddOn.Clear
  FMain.txtJournalTitleAddOn.Clear
  FMain.txtIssueTitleAddOn.Clear
  FMain.txtEventTitleAddOn.Clear
  FMain.txtChapter.Clear
  FMain.txtORIGDATE.Clear
  FMain.txtVERSION.Clear
  FMain.txtGENDER.Clear
  FMain.txtINDEXTITLE.Clear
  FMain.txtISSUETITLE.Clear
  FMain.txtREPRINTTITLE.Clear
  FMain.txtVENUE.Clear
  FMain.txtLANGIDOPTS.Clear
  FMain.txtISAN.Clear
  FMain.txtXREF.Clear
  FMain.txtXDATA.Clear
  FMain.txtPRESORT.Clear
  FMain.txtSORTKEY.Clear
  FMain.txtSORTNAME.Clear
  FMain.txtSORTSHORTHAND.Clear
  FMain.txtSORTTITLE.Clear
  FMain.txtINDEXSORTTITLE.Clear
  FMain.txtSORTYEAR.Clear
  FMain.txtFILE.Clear
  FMain.txtABSTRACT.Clear
  FMain.txtORIGLOCATION.Clear
  FMain.txtORIGPUBLISHER.Clear
  FMain.txtISMN.Clear
  FMain.txtISRN.Clear
  FMain.txtISWC.Clear
  FMain.txtEID.Clear
  FMain.txtEPRINT.Clear
  FMain.txtENTRYSUBTYPE.Clear
  FMain.txtHOWPUBLISHED.Clear
  FMain.txtADDENDUM.Clear
  FMain.txtSHORTHAND.Clear
  FMain.txtSHORTHANDINTRO.Clear
  FMain.txtIDS.Clear
  FMain.txtENTRYSET.Clear
  FMain.txtNOTE.Clear
  FMain.txtTitleAddOn.Clear
  FMain.txtSubTitle.Clear

End

Public Sub LimpiarCamposGitHubPages()

  FMain.txtCreateDateHTML.Clear
  FMain.txtModDateHTML.Clear
  FMain.txtCVautoresHTML.Clear
  FMain.txtHREFepubHTML.Clear
  FMain.txtHREFenlineaHTML.Clear
  FMain.txtHREFpdfHTML.Clear
  FMain.txtImagenHTML.Clear
  FMain.txtPubDateHTML.Clear
  FMain.txtPieHTML.Clear
  FMain.txtCabeceraHTML.Clear
  FMain.txtSumarioHTML.Clear

End

Public Function LimpiarCamposNotas()

  Form_Notas.txtBuscar.Clear
  Form_Notas.txId.Clear
  Form_Notas.txAsunto.Clear
  Form_Notas.txContenido.Clear

End

Public Sub EliminarEspaciosAlInicioYFinal(textbox As TextBox)

  Dim texto As String

  texto = textbox.Text
  texto = Trim$(texto)
  textbox.Text = texto

End

Public Sub eliminarBlancosBIB()

  EliminarEspaciosAlInicioYFinal(FMain.txtETIQ)
  EliminarEspaciosAlInicioYFinal(FMain.txtKEYWORDS)
  EliminarEspaciosAlInicioYFinal(FMain.txtCROSSREF)
  EliminarEspaciosAlInicioYFinal(FMain.txtCLAVEbib)
  EliminarEspaciosAlInicioYFinal(FMain.txtTITLE)
  EliminarEspaciosAlInicioYFinal(FMain.txtRELATED)
  EliminarEspaciosAlInicioYFinal(FMain.txtYEAR)
  EliminarEspaciosAlInicioYFinal(FMain.txtDATEY)
  EliminarEspaciosAlInicioYFinal(FMain.txtPUBLISHER)
  EliminarEspaciosAlInicioYFinal(FMain.txtLOCATION)
  EliminarEspaciosAlInicioYFinal(FMain.txtEDITOR)
  EliminarEspaciosAlInicioYFinal(FMain.txtSERIES)
  EliminarEspaciosAlInicioYFinal(FMain.txtRELATEDSTRING)
  EliminarEspaciosAlInicioYFinal(FMain.txtMAINTITLE)
  EliminarEspaciosAlInicioYFinal(FMain.txtLABEL)
  EliminarEspaciosAlInicioYFinal(FMain.txtSHORTTITLE)
  EliminarEspaciosAlInicioYFinal(FMain.txtEDITION)
  EliminarEspaciosAlInicioYFinal(FMain.txtBOOKAUTHOR)
  EliminarEspaciosAlInicioYFinal(FMain.txtBOOKTITLE)
  EliminarEspaciosAlInicioYFinal(FMain.txtVOLUME)
  EliminarEspaciosAlInicioYFinal(FMain.txtNUMBER)
  EliminarEspaciosAlInicioYFinal(FMain.txtPAGES)
  EliminarEspaciosAlInicioYFinal(FMain.txtJOURNALTITLE)
  EliminarEspaciosAlInicioYFinal(FMain.txtURLDATE)
  EliminarEspaciosAlInicioYFinal(FMain.txtDOI)
  EliminarEspaciosAlInicioYFinal(FMain.txtPART)
  EliminarEspaciosAlInicioYFinal(FMain.txtBOLUMES)
  EliminarEspaciosAlInicioYFinal(FMain.txtPAGETOTAL)
  EliminarEspaciosAlInicioYFinal(FMain.txtISBN)
  EliminarEspaciosAlInicioYFinal(FMain.txtISSN)
  EliminarEspaciosAlInicioYFinal(FMain.txtORGANIZATION)
  EliminarEspaciosAlInicioYFinal(FMain.txtINSTITUTION)
  EliminarEspaciosAlInicioYFinal(FMain.txtEVENTTITLE)
  EliminarEspaciosAlInicioYFinal(FMain.txtEVENTDATE)
  EliminarEspaciosAlInicioYFinal(FMain.txtINTRODUCTION)
  EliminarEspaciosAlInicioYFinal(FMain.txtTRANSLATOR)
  EliminarEspaciosAlInicioYFinal(FMain.txtAFTERWORD)
  EliminarEspaciosAlInicioYFinal(FMain.txtFOREWORD)
  EliminarEspaciosAlInicioYFinal(FMain.txtURL)
  EliminarEspaciosAlInicioYFinal(FMain.txtCOMMENTATOR)
  EliminarEspaciosAlInicioYFinal(FMain.txtANNOTATOR)
  EliminarEspaciosAlInicioYFinal(FMain.txtNAMEADDON)
  EliminarEspaciosAlInicioYFinal(FMain.txtAUTHOR)
  EliminarEspaciosAlInicioYFinal(FMain.txtEDITORa)
  EliminarEspaciosAlInicioYFinal(FMain.txtEDITORb)
  EliminarEspaciosAlInicioYFinal(FMain.txtEDITORc)
  EliminarEspaciosAlInicioYFinal(FMain.txtHOLDER)
  EliminarEspaciosAlInicioYFinal(FMain.txtShortAuthor)
  EliminarEspaciosAlInicioYFinal(FMain.txtBookTitleAddOn)
  EliminarEspaciosAlInicioYFinal(FMain.txtMainTitleAddOn)
  EliminarEspaciosAlInicioYFinal(FMain.txtJournalTitleAddOn)
  EliminarEspaciosAlInicioYFinal(FMain.txtIssueTitleAddOn)
  EliminarEspaciosAlInicioYFinal(FMain.txtEventTitleAddOn)
  EliminarEspaciosAlInicioYFinal(FMain.txtChapter)
  EliminarEspaciosAlInicioYFinal(FMain.txtORIGDATE)
  EliminarEspaciosAlInicioYFinal(FMain.txtVERSION)
  EliminarEspaciosAlInicioYFinal(FMain.txtGENDER)
  EliminarEspaciosAlInicioYFinal(FMain.txtINDEXTITLE)
  EliminarEspaciosAlInicioYFinal(FMain.txtISSUETITLE)
  EliminarEspaciosAlInicioYFinal(FMain.txtREPRINTTITLE)
  EliminarEspaciosAlInicioYFinal(FMain.txtVENUE)
  EliminarEspaciosAlInicioYFinal(FMain.txtLANGIDOPTS)
  EliminarEspaciosAlInicioYFinal(FMain.txtISAN)
  EliminarEspaciosAlInicioYFinal(FMain.txtXREF)
  EliminarEspaciosAlInicioYFinal(FMain.txtXDATA)
  EliminarEspaciosAlInicioYFinal(FMain.txtPRESORT)
  EliminarEspaciosAlInicioYFinal(FMain.txtSORTKEY)
  EliminarEspaciosAlInicioYFinal(FMain.txtSORTNAME)
  EliminarEspaciosAlInicioYFinal(FMain.txtSORTSHORTHAND)
  EliminarEspaciosAlInicioYFinal(FMain.txtSORTTITLE)
  EliminarEspaciosAlInicioYFinal(FMain.txtINDEXSORTTITLE)
  EliminarEspaciosAlInicioYFinal(FMain.txtSORTYEAR)
  EliminarEspaciosAlInicioYFinal(FMain.txtFILE)
  EliminarEspaciosAlInicioYFinal(FMain.txtORIGLOCATION)
  EliminarEspaciosAlInicioYFinal(FMain.txtORIGPUBLISHER)
  EliminarEspaciosAlInicioYFinal(FMain.txtISMN)
  EliminarEspaciosAlInicioYFinal(FMain.txtISRN)
  EliminarEspaciosAlInicioYFinal(FMain.txtISWC)
  EliminarEspaciosAlInicioYFinal(FMain.txtEID)
  EliminarEspaciosAlInicioYFinal(FMain.txtEPRINT)
  EliminarEspaciosAlInicioYFinal(FMain.txtENTRYSUBTYPE)
  EliminarEspaciosAlInicioYFinal(FMain.txtHOWPUBLISHED)
  EliminarEspaciosAlInicioYFinal(FMain.txtADDENDUM)
  EliminarEspaciosAlInicioYFinal(FMain.txtSHORTHAND)
  EliminarEspaciosAlInicioYFinal(FMain.txtSHORTHANDINTRO)
  EliminarEspaciosAlInicioYFinal(FMain.txtIDS)
  EliminarEspaciosAlInicioYFinal(FMain.txtENTRYSET)
  EliminarEspaciosAlInicioYFinal(FMain.txtTitleAddOn)

End

Public Sub eliminarBlancosGLO()

  EliminarEspaciosAlInicioYFinal(FMain.txtARCHIVO)
  EliminarEspaciosAlInicioYFinal(FMain.txtNAME)
  EliminarEspaciosAlInicioYFinal(FMain.txtDESCRIPTION)
  EliminarEspaciosAlInicioYFinal(FMain.txtFIRST)
  EliminarEspaciosAlInicioYFinal(FMain.txtTEXT)
  EliminarEspaciosAlInicioYFinal(FMain.txtPLURAL)
  EliminarEspaciosAlInicioYFinal(FMain.txtFPLURAL)
  EliminarEspaciosAlInicioYFinal(FMain.txtSORT)

End

Public Sub eliminarBlancosMETA()

  EliminarEspaciosAlInicioYFinal(FMain.txt05_pdfauthor)
  EliminarEspaciosAlInicioYFinal(FMain.txt06_pdftitle)

End
