' Gambas module file

Public rutaApp As String = User.Home &/ ".gbtexpublisher"
Public rutaAppR As String = User.Home &/ ".respaldogbTeX"
Public rutaScriptsExternos As String = User.Home &/ ".gbtexpublisher/ScriptsExternos"

Public Sub CopiarArchivos(rutaTexto As String)'libros

  ' usar Exist cuando refiere a directorios y File.RealPath cuando refiere a archivos
  If Not Exist(File.Dir(rutaTexto) & "/files") Then
    Mkdir File.Dir(rutaTexto) & "/files"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/correcciones") Then
    Mkdir File.Dir(rutaTexto) & "/correcciones"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/media") Then
    Mkdir File.Dir(rutaTexto) & "/media"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/originales") Then
    Mkdir File.Dir(rutaTexto) & "/originales"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/tapa") Then
    Mkdir File.Dir(rutaTexto) & "/tapa"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/pdf") Then
    Mkdir File.Dir(rutaTexto) & "/pdf"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/artcap") Then
    Mkdir File.Dir(rutaTexto) & "/artcap"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/docs") Then
    Mkdir File.Dir(rutaTexto) & "/docs"
  End If

  'copiamos los archivos de preámbulo de libro
  If Not File.RealPath(File.Dir(rutaTexto) & "/files/book-pdf.tex") Then
    Copy "./book-pdf.tex" To File.Dir(rutaTexto) & "/files/book-pdf.tex"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/files/book-xml.tex") Then
    Copy "./book-xml.tex" To File.Dir(rutaTexto) & "/files/book-xml.tex"
  End If

  'copiamos los archivos de configuracion general
  If Not File.RealPath(File.Dir(rutaTexto) & "/files/imagoCustom.css") Then
    Copy "./imagoCustom.css" To File.Dir(rutaTexto) & "/files/imagoCustom.css"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/files/imagoEpub.css") Then
    Copy "./imagoEpub.css" To File.Dir(rutaTexto) & "/files/imagoEpub.css"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/artcap/inicio-frontmatter.tex") Then
    Copy "./inicio-frontmatter.tex" To File.Dir(rutaTexto) & "/artcap/inicio-frontmatter.tex"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/artcap/agradecimientos.tex") Then
    Copy "./agradecimientos.tex" To File.Dir(rutaTexto) & "/artcap/agradecimientos.tex"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/artcap/colofon.tex") Then
    Copy "./colofon.tex" To File.Dir(rutaTexto) & "/artcap/colofon.tex"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/artcap/indiceautores.tex") Then
    Copy "./indiceautores.tex" To File.Dir(rutaTexto) & "/artcap/indiceautores.tex"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/readme.md") Then
    Copy "./readme.md" To File.Dir(rutaTexto) & "/readme.md"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/LICENSE") Then
    Copy "./LICENSE2" To File.Dir(rutaTexto) & "/LICENSE"
  End If

  If Not File.RealPath(File.Dir(rutaTexto) & "/media/logo-imago-ByW.png") Then
    Copy "./logo-imago-ByW.png" To File.Dir(rutaTexto) & "/media/logo-imago-ByW.png"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/media/desconocido.png") Then
    Copy "./desconocido.png" To File.Dir(rutaTexto) & "/media/desconocido.png"
  End If

  ' copiamos archivos para página html
  If Not File.RealPath(File.Dir(rutaTexto) & "/docs/logo-imago.png") Then
    Copy "./logo-imago.png" To File.Dir(rutaTexto) & "/docs/logo-imago.png"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/docs/descarga.png") Then
    Copy "./descarga.png" To File.Dir(rutaTexto) & "/docs/descarga.png"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/docs/orcid.png") Then
    Copy "./orcid.png" To File.Dir(rutaTexto) & "/docs/orcid.png"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/docs/imago1.css") Then
    Copy "./imago1.css" To File.Dir(rutaTexto) & "/docs/imago1.css"
  End If
  If Not File.RealPath(File.Dir(rutaTexto) & "/docs/favicon.jpg") Then
    Copy "./favicon.jpg" To File.Dir(rutaTexto) & "/docs/favicon.jpg"
  End If

End

Public Sub ManagePdfFolder(rutaTexto As String)

  Dim pdfPath As String = File.Dir(rutaTexto) & "/pdf"

  ' Verifica si la carpeta existe
  If Not Exist(pdfPath) Then
    ' Si no existe, crea la carpeta
    Mkdir pdfPath
  Else
    ' borramos todos los archivos pdf del proyecto
    Shell "rm -rf " & pdfPath & "/*.pdf" Wait
  End If

End Sub

Public Sub GitVersion(raw As String) As String 'Función para chequear si hay versiones nuevas

  Dim s As String
  Dim stx As String[]
  Dim r As String
  Dim v As String

  v = ""
  If File.RealPath("/tmp/project.txt") Then
    Shell "rm /tmp/project.txt" Wait
  Endif

  Shell "wget -O '/tmp/project.txt' '" & raw & "'" Wait
  If File.RealPath("/tmp/project.txt") Then
    s = File.Load("/tmp/project.txt")
    stx = Split(s, "\n")
    For Each r In stx
      If InStr(r, "Version=") Then
        If Split(r, "=")[0] = "Version" Then
          v = Split(r, "=")[1]
          Break
        Endif
      Endif
    Next
  Endif
  Return v

End

'funcion para asegurar metadatos basicos a los archivos
Public Function registrosObligatorios(rutaTexto As String) As Boolean

  Dim campo0, campo1, campo2, campo3, campo4, campo5, campo6, campo7 As String

  campo0 = FMain.txtnombreArchivo.Text
  campo1 = FMain.txt84_bookTitle.Text
  campo2 = FMain.txt05_pdfauthor.Text
  campo3 = FMain.txtDate.Text
  campo4 = FMain.txtSubjet.Text
  campo5 = FMain.txt57_palabrasclave.Text
  campo6 = FMain.txt10_pdfauthortitle.Text
  campo7 = FMain.txtCaptionWriter.Text

  ' Verificar si el campo de metadatos existe
  If campo0 = "" Then
    Message.Error("Debe asegurar la construcción del archivo de metadatos para <strong>" & File.Name(rutaTexto) & "</strong>", "Aceptar")
    FMain.TabPanel1.Index = 3
    Return False
  End If

  ' Verificamos si los otros campos están vacíos
  If campo1 = "" Or campo2 = "" Or campo3 = "" Or campo4 = "" Or campo5 = "" Or campo6 = "" Or campo7 = "" Then
    Message.Error("Uno o más registros de los metadatos obligatorios están vacíos, la operación será cancelada.", "Aceptar")
    FMain.TabPanel1.Index = 3
    Return False
  End If
  ' Si todo está bien, retornamos True
  Return True

End Function

Public Sub Borrar_Aux()

  FMain.TerminalView1.Input("cd " & File.Dir(FMain.TextBox1.Text) & "\n" & "rm *.xmpi *.*1 *.*2 *.*3 *.eledsec* *.*end *.fuse* odt-*.tex *.bcf-SAVE-ERROR html5-*_html.tex *.bbl-SAVE-ERROR html5-*.tex *.css *.lwarpmkconf *.sidetoc *.conf *.cut *.upa *.upb *.bib.backup *.ndx *.ps *.tex.backup *.bib *.csv *.published *.dat *.txt *.pdf *.bib.sav *.xml *.html *.xhtml *.opf *.xref *.ncx *.tmp *.4ct *.4tc *.4of *.4ot *.4os *.4oy *.4oo *.4og *.lg *.idv *.acn *.acr *.alg *.glg *.gls *.ist *.bak *.log *.aux *.dvi *.lof *.lot *.bit *.idx *.glo *.bbl *.bcf *.ilg *.toc *.ind *.out *.blg *.fdb_latexmk *.fls *.run.xml *.ida *.idn *.inn *.synctex.gz *.xdy *.opf *.epub *.mobi *.ent *.cfg *.lua *.mk4 *.png *.jpg *.svg" & "\n" & "clear" & "\n") 'desde la raiz al directorio padre
  Wait 0.2

  FMain.TerminalView1.SetFocus()

End

Public Sub limpiamosMetadatosLibrosRevistas()

  FMain.txtIdmetadatos.Text = ""
  FMain.txtnombreArchivo.Text = ""
  FMain.txt02_pdfxmp1.Text = ""
  FMain.txt03_pdfxmp2.Text = ""
  FMain.txt04_pdfxmp3.Text = ""
  FMain.txt05_pdfauthor.Text = ""
  FMain.txt06_pdftitle.Text = ""
  FMain.txtSubjet.Text = ""
  FMain.txtKeywords.Text = ""
  FMain.txt09_pdfsubtitle.Text = ""
  FMain.txt10_pdfauthortitle.Text = ""
  FMain.txtDate.Text = ""
  FMain.txtCreationDate.Text = ""
  FMain.txtModDate.Text = ""
  FMain.txtMetaDate.Text = ""
  FMain.txt15_pdfcopyright.Text = ""
  FMain.txt16_pdflicenseurl.Text = ""
  FMain.txtCaptionWriter.Text = ""
  FMain.txtContactAddress.Text = ""
  FMain.txtContactCity.Text = ""
  FMain.txtContactPostCode.Text = ""
  FMain.txtContactCountry.Text = ""
  FMain.txtContactRegion.Text = ""
  FMain.txtContactPhone.Text = ""
  FMain.txtContactEmail.Text = ""
  FMain.txtContactURL.Text = ""
  FMain.txtDocumentId.Text = ""
  FMain.txtPublication.Text = ""
  FMain.txtPublisher.Text = ""
  FMain.cmbType.Text = ""
  FMain.cbPubType.Text = ""
  FMain.txtVolNum.Text = ""
  FMain.txtIssueNum.Text = ""
  FMain.txt33_pdfpagerange.Text = ""
  FMain.txt34_pdfbookedition.Text = ""
  FMain.txt35_pdfisbn.Text = ""
  FMain.txt36_pdfissn.Text = ""
  FMain.txt37_pdfeissn.Text = ""
  FMain.txt38_pdfpubstatus.Text = ""
  FMain.txtLang.Text = ""
  FMain.txt40_pdfmetalang.Text = ""
  FMain.txtBaseURL.Text = ""
  FMain.txt42_pdfurl.Text = ""
  FMain.txt43_pdfdoi.Text = ""
  FMain.cbPDFrendition.Text = ""
  FMain.txtDocumentId.Text = ""
  FMain.cbPDFx.Text = ""
  FMain.txtVersionId.Text = ""
  FMain.txt48_abstract.Text = ""
  FMain.txt49_imagentapa.Text = ""
  FMain.txt50_pagetotal.Text = ""
  FMain.txtCOLECCION.Text = ""
  FMain.txtDirection.Text = ""
  FMain.txt53_traductor.Text = ""
  FMain.txt54_idiomaorig.Text = ""
  FMain.txt55_ilustrador.Text = ""
  FMain.txt56_resumen.Text = ""
  FMain.txt57_palabrasclave.Text = ""
  FMain.txt58_papertitletwo.Text = ""
  FMain.txt59_artrecibido.Text = ""
  FMain.txt60_artaceptado.Text = ""
  FMain.txtFORMATO.Text = ""
  FMain.txt59_opt_source.Text = ""
  FMain.txt82_conferenceVisual.Text = ""
  FMain.txt78_genero.Text = ""
  FMain.txt82_conference.Text = ""
  FMain.txt84_bookTitle.Text = ""
  FMain.txt85_doiRevista.Text = ""
  FMain.txt86_annotation.Text = ""
  FMain.txt87_HTMLFirstPageBottom.Text = ""
  FMain.txt88_audiencia.Text = ""
  FMain.txt89_binding.Text = ""
  FMain.txt90_eisbn.Text = ""

End

Public Sub VerificarPorcentajeEnTexto(TextoOriginal As String) As String

  Dim nuevoTexto As String

  nuevoTexto = TextoOriginal

  ' hacemos reemplazos de seguridad
  nuevoTexto = Replace(nuevoTexto, "%", "\\%")
  nuevoTexto = Replace(nuevoTexto, "´", "'")
  nuevoTexto = Replace(nuevoTexto, "’", "'")

  ' Devolvemos el texto modificado
  Return nuevoTexto

End
