' Gambas module file

Private BaseName As String = File.BaseName(FMain.TextBox1.Text)
Private rutaFILES As String = File.Dir(FMain.TextBox1.Text) & "/files"

Public Sub salidaEPUBpng()

  ' obtenemos la exportación de los archivos bib, glo, metadatos y separata
  Mod_Exportar.ExportToSeparata(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2BibTeX(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2Glosario(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2MetadatosPDF(FMain.TextBox1.Text)
  Wait 0.2

  Mod_Funciones.Borrar_Aux
  Wait 0.2

  ' Lista de directorios que deseas crear dentro de "ebook"
  Dim directorios As String[] = ["kindle", "png", "epub1"]

  ' Asegurarse de que el directorio "ebook" existe
  If Not Exist(File.Dir(FMain.TextBox1.Text) & "/ebook") Then
    Mkdir File.Dir(FMain.TextBox1.Text) & "/ebook"
  End If

  ' Crear los subdirectorios dentro de "ebook" si no existen
  For Each directorio As String In directorios
    If Not Exist(File.Dir(FMain.TextBox1.Text) & "/ebook/" & directorio) Then
      Mkdir File.Dir(FMain.TextBox1.Text) & "/ebook/" & directorio
    End If
  Next

  Dim condicional As String = "\\\\PNGEPUBtrue"
  FMain.TerminalView1.Input("echo " & condicional & " >> " & rutaFILES & "/book-epub1.tex" & "\n")

  Dim newFile As String = "epub1-" & BaseName & ".tex"  ' generamos el archivo tex
  FMain.TerminalView1.Input("cat " & rutaFILES & "/book-epub1.tex " & File.Name(FMain.TextBox1.Text) & " > " & newFile & "\n")
  Wait 0.2

  Dim limpiarCondicional As String
  limpiarCondicional = "sed -i '/\\\\PNGEPUBtrue/d' " & rutaFILES & "/book-epub1.tex" & "\n"
  FMain.TerminalView1.Input(limpiarCondicional)

  Dim compilar As String
  compilar = "latexmk -l -f --interaction=nonstopmode -pdflatex=lualatex -pdflua " & newFile & "\n"
  FMain.TerminalView1.Input(compilar)
  Wait 0.2

  ' borramos el archivo que usamos para compilar
  FMain.TerminalView1.Input("rm -rf " & newFile & "\n")
  Wait 0.2

  'eliminamos los archivos auxiliares
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/artcap/*.aux" & "\n")
  Wait 0.2

  ' movemos el pdf al directorio epub1
  FMain.TerminalView1.Input("mv " & File.Dir(FMain.TextBox1.Text) & "/epub1-" & BaseName & ".pdf" & " " & File.Dir(FMain.TextBox1.Text) & "/ebook/epub1-" & BaseName & ".pdf" & "\n")
  Wait 0.2

  ' generamos las imagenes png
  FMain.TerminalView1.Input("gs -sDEVICE=pngmono -r300 -o" & " " & File.Dir(FMain.TextBox1.Text) & "/ebook/png/pagina_%03d.png" & " " & File.Dir(FMain.TextBox1.Text) & "/ebook/epub1-" & BaseName & ".pdf" & "\n")
  Wait 0.2

  ' generamos el epub

  ' validamos el epub con un condicional para usar un mensaje de info

  ' ' si la validación dio bien generamos un azw3 usando calibre
  ' FMain.TerminalView1.Input("ebook-convert" & " " & File.Dir(rutaTexto) & "/ebook/epub1/epub1-pdf-" & BaseName & ".epub" & " " & File.Dir(rutaTexto) & "/ebook/kindle/kindle-pdf-" & BaseName & ".azw3" & "\n")
  ' Wait 0.2

  'eliminamos los archivos bib y glo
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/files/gbTeXglo-" & File.BaseName(FMain.TextBox1.Text) & ".tex" & "\n")
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/files/gbTeXbib-" & File.BaseName(FMain.TextBox1.Text) & ".bib" & "\n")
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/files/gbTeXmeta-" & File.BaseName(FMain.TextBox1.Text) & ".tex" & "\n")
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/files/gbTeXseparata-" & File.BaseName(FMain.TextBox1.Text) & ".tex" & "\n")
  Wait 0.2

  ' borramos los archivos auxiliares
  Mod_Funciones.Borrar_Aux

End

Public Sub salidaEPUBhtml()

  ' Lista de directorios que deseas crear dentro de "ebook"
  Dim directorios As String[] = ["kindle", "epub3"]

  ' Asegurarse de que el directorio "ebook" existe
  If Not Exist(File.Dir(FMain.TextBox1.Text) & "/ebook") Then
    Mkdir File.Dir(FMain.TextBox1.Text) & "/ebook"
  End If

  ' Crear los subdirectorios dentro de "ebook" si no existen
  For Each directorio As String In directorios
    If Not Exist(File.Dir(FMain.TextBox1.Text) & "/ebook/" & directorio) Then
      Mkdir File.Dir(FMain.TextBox1.Text) & "/ebook/" & directorio
    End If
  Next

  Dim newFile As String = "epub3-" & BaseName & ".tex"

  ' generamos el archivo tex y compilamos el pdf
  FMain.TerminalView1.Input("cat " & rutaFILES & "/book-epub3.tex " & File.Name(FMain.TextBox1.Text) & " > " & newFile & "\n")
  Wait 0.2

  ' exportamos los archivos bib, glo y meta
  Mod_Exportar.Exportar2BibTeX(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2Glosario(FMain.TextBox1.Text)
  Mod_Exportar.Export2MetaEPUB(FMain.TextBox1.Text)
  Wait 0.2

  FMain.TerminalView1.Input("cat " & rutaFILES & "/configEPUB.cfg " & rutaFILES & "/gbTeXmeta-" & BaseName & ".tex" & " > " & rutaFILES & "/gbTeXmeta-" & BaseName & ".cfg" & "\n")
  Wait 0.2

  FMain.TerminalView1.Input("tex4ebook -l -f epub -e " & rutaFILES & "/build.lua -c " & rutaFILES & "/gbTeXmeta-" & BaseName & ".cfg -a Debug " & "epub-" & File.Name(FMain.TextBox1.Text) & "\n" & "rm -rf " & newFile & "\n")
  Wait 0.2

  ' si la validación dio bien generamos un azw3 usando calibre
  FMain.TerminalView1.Input("ebook-convert" & " " & File.Dir(FMain.TextBox1.Text) & "/ebook/epub1/epub1-pdf-" & BaseName & ".epub" & " " & File.Dir(FMain.TextBox1.Text) & "/ebook/kindle/kindle-pdf-" & BaseName & ".azw3" & "\n")
  Wait 0.2

  ' FMain.TerminalView1.Input("mv epub-" & folder & " epub" & "\n" & "clear" & "\n")
  ' Wait 0.2

  ' FMain.TerminalView1.Input("rm -rf " & rutaFILES & "/gbTeXmeta-" & BaseName & ".cfg" & "\n")
  ' Wait 0.2

  FMain.TerminalView1.SetFocus()
  Mod_Funciones.Borrar_Aux

End
