' Gambas module file

Public rutaFILES As String = File.Dir(FMain.TextBox1.Text) & "/files"

Public Sub salidaPDFweb() 'generamos el PDF web del libro

  FMain.DirViewRuta.Refresh
  FMain.FileViewProyecto.Refresh

  Dim newFile As String
  Dim newLog As String

  ' Llamamos a la función del módulo para verificar los metadatos obligatorios
  If Not Mod_Funciones.registrosObligatorios(FMain.TextBox1.Text) Then
    ' Si la función retorna False, cancelamos la operación
    Return
  End If

  newFile = "pdf-" & File.BaseName(FMain.TextBox1.Text) & ".tex"
  newLog = "gbTeX-" & File.BaseName(FMain.TextBox1.Text) & ".log"

  Mod_Funciones.Borrar_Aux
  Wait 0.2

  FMain.TabPanel1.Index = 0
  FMain.TabPanel6.Index = 0

  ' obtenemos la exportación de los archivos bib, glo, metadatos y separata
  Mod_Exportar.ExportToSeparata(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2BibTeX(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2Glosario(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2MetadatosPDF(FMain.TextBox1.Text)
  Wait 0.2

  'revisamos la carpeta pdf y borramos el archivo
  Mod_Funciones.ManagePdfFolder(FMain.TextBox1.Text)

  Dim condicional As String = "\\\\PDFtrue"
  FMain.TerminalView1.Input("echo " & condicional & " >> " & File.Dir(FMain.TextBox1.Text) & "/files" & "/book-pdf.tex" & "\n")

  FMain.TerminalView1.Input("cat " & File.Dir(FMain.TextBox1.Text) & "/files" & "/book-pdf.tex" & " " & File.Name(FMain.TextBox1.Text) & " > " & newFile & "\n")
  Wait 0.2

  Dim limpiarCondicional As String
  limpiarCondicional = "sed -i '/\\\\PDFtrue/d' " & File.Dir(FMain.TextBox1.Text) & "/files" & "/book-pdf.tex" & "\n"
  FMain.TerminalView1.Input(limpiarCondicional)

  Dim compilar As String
  compilar = "latexmk -l -f --interaction=nonstopmode -pdflatex=lualatex -pdflua " & newFile & "\n"
  ' Envía el comando al terminal
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/pdf/metadatospdf-" & File.BaseName(FMain.TextBox1.Text) & ".txt" & "\n")
  FMain.TerminalView1.Input(compilar)
  Wait 0.2

  FMain.TerminalView1.Input("rm -rf " & newFile & "\n")
  Wait 0.2

  FMain.TerminalView1.Input("mv " & File.Dir(FMain.TextBox1.Text) & "/pdf-" & File.BaseName(FMain.TextBox1.Text) & ".pdf" & " " & File.Dir(FMain.TextBox1.Text) & "/pdf/pdf-" & File.BaseName(FMain.TextBox1.Text) & ".pdf" & "\n")
  Wait 0.2

  'copiamos /files el archivo .log
  FMain.TerminalView1.Input("cat pdf-" & File.BaseName(FMain.TextBox1.Text) & ".log > " & rutaFILES & "/gbTeX-" & File.BaseName(FMain.TextBox1.Text) & ".log" & "\n")
  Wait 0.2

  'eliminamos los archivos auxiliares
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/artcap/*.aux" & "\n")
  Wait 0.2

  'eliminamos los archivos bib y glo
  Mod_Funciones.Borrar_Aux
  Wait 0.2
  FMain.DirViewRuta.Reload
  FMain.FileViewProyecto.Reload

End

Public Sub salidaPDFimprenta() 'generamos el PDF imprenta del libro

  FMain.DirViewRuta.Refresh
  FMain.FileViewProyecto.Refresh

  Dim newFile As String
  Dim newLog As String

  Mod_Funciones.Borrar_Aux
  Wait 0.2

  ' Llamamos a la función del módulo para verificar los metadatos obligatorios
  If Not Mod_Funciones.registrosObligatorios(FMain.TextBox1.Text) Then
    ' Si la función retorna False, cancelamos la operación
    Return
  End If

  newFile = "pdf-" & File.BaseName(FMain.TextBox1.Text) & ".tex"
  newLog = "gbTeX-" & File.BaseName(FMain.TextBox1.Text) & ".log"

  FMain.TabPanel1.Index = 0
  FMain.TabPanel6.Index = 0
  ' obtenemos la exportación de los archivos bib, glo, metadatos y separata
  Mod_Exportar.ExportToSeparata(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2BibTeX(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2Glosario(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2MetadatosPDF(FMain.TextBox1.Text)
  Wait 0.2

  'revisamos la carpeta pdf y borramos el archivo
  Mod_Funciones.ManagePdfFolder(FMain.TextBox1.Text)

  Dim condicional As String = "\\\\BNPDFtrue"
  FMain.TerminalView1.Input("echo " & condicional & " >> " & File.Dir(FMain.TextBox1.Text) & "/files" & "/book-pdf.tex" & "\n")

  FMain.TerminalView1.Input("cat " & File.Dir(FMain.TextBox1.Text) & "/files" & "/book-pdf.tex" & " " & File.Name(FMain.TextBox1.Text) & " > " & newFile & "\n")
  Wait 0.2

  Dim limpiarCondicional As String
  limpiarCondicional = "sed -i '/\\\\BNPDFtrue/d' " & File.Dir(FMain.TextBox1.Text) & "/files" & "/book-pdf.tex" & "\n"
  FMain.TerminalView1.Input(limpiarCondicional)

  Dim compilar As String
  compilar = "latexmk -l -f --interaction=nonstopmode -pdflatex=lualatex -pdflua " & newFile & "\n"
  FMain.TerminalView1.Input(compilar)
  Wait 0.2

  FMain.TerminalView1.Input("rm -rf " & newFile & "\n")
  Wait 0.2

  FMain.TerminalView1.Input("mv " & File.Dir(FMain.TextBox1.Text) & "/pdf-" & File.BaseName(FMain.TextBox1.Text) & ".pdf" & " " & File.Dir(FMain.TextBox1.Text) & "/pdf/pdf-" & File.BaseName(FMain.TextBox1.Text) & ".pdf" & "\n")
  Wait 0.2

  'copiamos /files el archivo .log
  FMain.TerminalView1.Input("cat pdf-" & File.BaseName(FMain.TextBox1.Text) & ".log > " & rutaFILES & "/gbTeX-" & File.BaseName(FMain.TextBox1.Text) & ".log" & "\n")
  Wait 0.2

  'eliminamos los archivos auxiliares
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/artcap/*.aux" & "\n")
  Wait 0.2

  Mod_Funciones.Borrar_Aux
  Wait 0.2
  FMain.DirViewRuta.Reload
  FMain.FileViewProyecto.Reload

End

Public Sub salidaPDFespecial() 'generamos el PDF customizado

  FMain.DirViewRuta.Refresh
  FMain.FileViewProyecto.Refresh

  Dim newFile As String
  Dim newLog As String

  ' Llamamos a la función del módulo para verificar los metadatos obligatorios
  If Not Mod_Funciones.registrosObligatorios(FMain.TextBox1.Text) Then
    ' Si la función retorna False, cancelamos la operación
    Return
  End If

  newFile = "pdf-" & File.BaseName(FMain.TextBox1.Text) & ".tex"
  newLog = "gbTeX-" & File.BaseName(FMain.TextBox1.Text) & ".log"

  Mod_Funciones.Borrar_Aux
  Wait 0.2

  FMain.TabPanel1.Index = 0
  FMain.TabPanel6.Index = 0

  ' obtenemos la exportación de los archivos bib, glo, metadatos y separata
  Mod_Exportar.ExportToSeparata(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2BibTeX(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2Glosario(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2MetadatosPDF(FMain.TextBox1.Text)
  Wait 0.2

  'revisamos la carpeta pdf y borramos el archivo
  Mod_Funciones.ManagePdfFolder(FMain.TextBox1.Text)

  Dim condicional As String = "\\\\PDFtrue"
  FMain.TerminalView1.Input("echo " & condicional & " >> " & File.Dir(FMain.TextBox1.Text) & "/files" & "/book-pdf-especial.tex" & "\n")

  ' generamos el nuevo archivo
  FMain.TerminalView1.Input("cat " & File.Dir(FMain.TextBox1.Text) & "/files" & "/book-pdf-especial.tex" & " " & File.Name(FMain.TextBox1.Text) & " > " & newFile & "\n")
  Wait 0.2

  Dim limpiarCondicional As String
  limpiarCondicional = "sed -i '/\\\\PDFtrue/d' " & File.Dir(FMain.TextBox1.Text) & "/files" & "/book-pdf-especial.tex" & "\n"
  FMain.TerminalView1.Input(limpiarCondicional)

  Dim compilar As String
  compilar = "latexmk -l -f --interaction=nonstopmode -pdflatex=lualatex -pdflua " & newFile & "\n"
  ' Envía el comando al terminal
  FMain.TerminalView1.Input(compilar)
  Wait 0.2

  FMain.TerminalView1.Input("rm -rf " & newFile & "\n")
  Wait 0.2

  FMain.TerminalView1.Input("mv " & File.Dir(FMain.TextBox1.Text) & "/pdf-" & File.BaseName(FMain.TextBox1.Text) & ".pdf" & " " & File.Dir(FMain.TextBox1.Text) & "/pdf/pdf-" & File.BaseName(FMain.TextBox1.Text) & ".pdf" & "\n")
  Wait 0.2

  'copiamos /files el archivo .log
  FMain.TerminalView1.Input("cat pdf-" & File.BaseName(FMain.TextBox1.Text) & ".log > " & rutaFILES & "/gbTeX-" & File.BaseName(FMain.TextBox1.Text) & ".log" & "\n")
  Wait 0.2

  'eliminamos los archivos auxiliares
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/artcap/*.aux" & "\n")
  Wait 0.2

  Mod_Funciones.Borrar_Aux
  Wait 0.2
  FMain.DirViewRuta.Reload
  FMain.FileViewProyecto.Reload

End
