' Gambas module file

'combobox de sigla y glosario
Public Function cbTYPEentradaGlo() As String[]

  Return ["sigla", "glosario"]

End Function

'combobox de tipo de entrada en bibliografia
Public Function cbTYPEentrada() As String[]

  Return ["", "article", "incollection", "book", "thesis", "online", "inproceedings", "mvbook", "inbook", "bookinbook", "suppbook", "booklet", "collection", "mvcollection", "suppcollection", "manual", "misc", "patent", "periodical", "suppperiodical", "proceedings", "mvproceedings", "reference", "mvreference", "inreference", "report", "set", "unpublished", "xdata", "movie"]

End Function

Public Function cbLANGUAGE() As String[]

  Return ["", "spanish", "portuguese", "french", "italian", "german", "english", "latin", "greek", "chinese", "norwegian", "swedish", "danish", "dutch", "japanese", "romanian", "armenian", "korean", "russian", "latin", "czech"]

End Function

Public Function cbRELATEDTYPE() As String[]

  Return ["", "reprintof", "translationof", "translatedas", "multivolume"]

End Function

Public Function cbPUBSTATE() As String[]

  Return ["", "mimeograph", "photocopy", "digitalprinting", "inpreparation", "submitted", "forthcoming", "inpress", "prepublished"]

End Function

Public Function cbType() As String[]

  Return ["", "@thesis (seleccionar)", "tifthesis", "mathesis", "phdthesis", "candthesis", "ingenieriathesis", "magisterthesis", "gradothesis", "licenciaturathesis", "especialthesis", "posgradothesis", " ", "@manual (seleccionar)", " ", "@patent (seleccionar)", " ", "@report (seleccionar)"]

End Function

Public Function cbEDITORTYPE() As String[]

  Return ["", "editor", "compiler", "direction", "founder", "continuator", "redactor", "reviser", "collaborator", "cordinator", "organizator"]

End Function

Public Function cmbEstiloReferencias() As String[]

  Return ["", "APA (7th edition)", "AMS Review", "IEEE (con URL)", "Vancouver"]

End Function
