' Gambas module file

Public BaseName As String = File.BaseName(FMain.TextBox1.Text)
Public BaseRuta As String = File.Dir(FMain.TextBox1.Text)
Public rutaFILES As String = File.Dir(FMain.TextBox1.Text) & "/files"

Public Sub salidaEPUBpng()' parte 1

  FMain.DirViewRuta.Refresh
  FMain.FileView1.Refresh

  ' obtenemos la exportación de los archivos bib, glo, metadatos y separata
  FMain.TabPanel1.Index = 0
  FMain.TabPanel6.Index = 0
  Mod_Exportar.ExportToSeparata(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2BibTeX(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2Glosario(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2MetadatosPDF(FMain.TextBox1.Text)
  Wait 0.2

  ' borramos el epub existente
  FMain.TerminalView1.Input("rm -rf epub1" & "\n")
  Wait 0.2

  ' Asegurarse de que el directorio "epub1" existe
  If Not Exist(File.Dir(FMain.TextBox1.Text) & "/epub1") Then
    Mkdir File.Dir(FMain.TextBox1.Text) & "/epub1"
  End If

  If Not File.RealPath(File.Dir(FMain.TextBox1.Text) & "/epub1/cover.png") Then
    Copy File.Dir(FMain.TextBox1.Text) & "/tapa/cover.png" To File.Dir(FMain.TextBox1.Text) & "/epub1/cover.png"
  End If

  Dim condicional As String = "\\\\PNGEPUBtrue"
  FMain.TerminalView1.Input("echo " & condicional & " >> " & rutaFILES & "/book-epub1.tex" & "\n")

  Dim newFile As String = "epub1-" & BaseName & ".tex"  ' generamos el archivo tex
  FMain.TerminalView1.Input("cat " & rutaFILES & "/book-epub1.tex " & File.Name(FMain.TextBox1.Text) & " > " & newFile & "\n")
  Wait 0.2

  Dim limpiarCondicional As String
  limpiarCondicional = "sed -i '/\\\\PNGEPUBtrue/d' " & rutaFILES & "/book-epub1.tex" & "\n"
  FMain.TerminalView1.Input(limpiarCondicional)

  Dim compilar As String
  compilar = "latexmk -l -f --interaction=nonstopmode -pdflatex=lualatex -pdflua " & newFile & "\n"
  FMain.TerminalView1.Input(compilar)
  Wait 0.2

  ' borramos el archivo que usamos para compilar
  FMain.TerminalView1.Input("rm -rf " & newFile & "\n")
  Wait 0.2

  'eliminamos los archivos auxiliares
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/artcap/*.aux" & "\n")
  Wait 0.2

  ' movemos el pdf al directorio epub1
  FMain.TerminalView1.Input("mv " & File.Dir(FMain.TextBox1.Text) & "/epub1-" & BaseName & ".pdf" & " " & File.Dir(FMain.TextBox1.Text) & "/epub1/epub1-" & BaseName & ".pdf" & "\n")
  Wait 0.2

  ' generamos las imagenes png
  FMain.TerminalView1.Input("gs -sDEVICE=png16m -r300 -dTextAlphaBits=4 -dGraphicsAlphaBits=4 -o" & " " & File.Dir(FMain.TextBox1.Text) & "/epub1/pagina_%03d.png" & " " & File.Dir(FMain.TextBox1.Text) & "/epub1/epub1-" & BaseName & ".pdf" & "\n")
  Wait 0.2

  ' borramos los archivos auxiliares
  Mod_Funciones.Borrar_Aux
  Wait 0.2
  FMain.DirViewRuta.Reload
  FMain.FileView1.Reload

End

Public Sub creacionEpubPNG()' parte 2

  Dim archivoHTML As File
  Dim imagenes As New String[]
  Dim imagen As String
  Dim rutaEPUB1 As String = File.Dir(FMain.TextBox1.Text) & "/epub1/"
  Dim rutaCover As String = File.RealPath(File.Dir(FMain.TextBox1.Text) & "/tapa/cover.png")
  Dim rutaCoverDestino As String = rutaEPUB1 & "cover.png"
  Dim rutaIndex As String = rutaEPUB1 & "index.html"
  Dim rutaOPF As String = rutaEPUB1 & "content.opf"

  FMain.DirViewRuta.Refresh
  FMain.FileView1.Refresh

  ' Verificar si la imagen de tapa ya está en el directorio EPUB1
  If Not File.RealPath(rutaCoverDestino) Then
    Copy rutaCover To rutaCoverDestino
  Endif

  ' Obtener la lista de imágenes del contenido
  For Each imagen In Dir(rutaEPUB1, "pagina_*.png")
    Print "Detectado:", imagen
    imagenes.Add(imagen)
  Next

  ' Ordenar la lista por nombre
  imagenes.Sort()

  If Not File.RealPath(rutaOPF) Then
    Copy "./content.opf" To rutaEPUB1 & "content.opf"
  End If

  If Not File.RealPath(rutaIndex) Then
    Copy "./index.html" To rutaEPUB1 & "index.html"
  End If

  archivoHTML = Open rutaEPUB1 & "index.html" For Write

  ' Escribir la declaración DOCTYPE y la estructura básica del HTML
  Print #archivoHTML, "<!DOCTYPE html>"
  Print #archivoHTML, "<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='es' lang='es'>"
  Print #archivoHTML, "<head>"
  Print #archivoHTML, "    <meta charset='UTF-8' />"
  Print #archivoHTML, "    <meta name=\"generator\" content=\"EPUB Generator\">"
  Print #archivoHTML, "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
  Print #archivoHTML, "    <html lang=\"es\">"
  Print #archivoHTML, "    <title>" & BaseName & "</title>"
  Print #archivoHTML, "    <style>"
  Print #archivoHTML, "    img{"
  Print #archivoHTML, "    max-width: 100 %;"
  Print #archivoHTML, "    height: auto;"
  Print #archivoHTML, "    }"
  Print #archivoHTML, "    </style>"
  Print #archivoHTML, "</head>"
  Print #archivoHTML, "<body>"
  ' Print #archivoHTML, "    <h1>" & BaseName & "</h1>"
  ' Print #archivoHTML, "    <p>Sumario.</p>"
  Print #archivoHTML, "</body>"
  Print #archivoHTML, "</html>"

  ' Agregar las imágenes del contenido en orden
  For Each imagen In imagenes
    Print "Agregando al HTML:", imagen
    Print #archivoHTML, "<img src='./" & imagen & "'/>"
  Next

  Close archivoHTML
  Wait 0.2

  Dim archivoOPF As File
  archivoOPF = Open rutaEPUB1 & "content.opf" For Write

  Print #archivoOPF, "<?xml version='1.0' encoding='UTF-8'?>"
  Print #archivoOPF, "<package xmlns='http://www.idpf.org/2007/opf' unique-identifier='bookid' version='3.0'>"
  Print #archivoOPF, "<metadata xmlns:dc='http://purl.org/dc/elements/1.1/'>"
  ' Print #archivoOPF, "<dc:title>" & Contenido[aFields[84]] & ": " & Contenido[aFields[9]] & "</dc:title>"
  ' Print #archivoOPF, "<dc:creator>" & ContenidoAutores[xFields[2]] & "</dc:creator>"
  ' Print #archivoOPF, "<dc:language>" & Contenido[aFields[54]] & "</dc:language>"
  ' Print #archivoOPF, "<<dc:identifier id=\"uuid\" opf:scheme=\"uuid\">urn:uuid:" & fechauuid & "</dc:identifier>"
  ' Print #archivoOPF, "<dc:identifier id=\"isbn\" opf:scheme=\"ISBN\">ISBN:" & Contenido[aFields[35]] & "</dc:identifier>"
  ' Print #archivoOPF, "<dc:identifier id=\"url\" opf:scheme=\"URL\">" & Contenido[aFields[41]] & "</dc:identifier>"

  Print #archivoOPF, "<dc:publisher>Mi Editorial</dc:publisher>"
  Print #archivoOPF, "<dc:description>Descripción del libro</dc:description>"
  Print #archivoOPF, "<dc:date>2023-10-01</dc:date>"
  Print #archivoOPF, "<dc:rights>Copyright © 2023 Mi Editorial. Todos los derechos reservados.</dc:rights>"
  Print #archivoOPF, "<dc:type>Text</dc:type>"
  Print #archivoOPF, "<dc:format>application/epub+zip</dc:format>"

  Print #archivoOPF, "<meta name='cover' content='cover-image'/>"
  Print #archivoOPF, "</metadata>"
  Print #archivoOPF, "<manifest>"
  Print #archivoOPF, "    <item id='cover-image' href='cover.png' media-type='image/png'/>"
  Print #archivoOPF, "    <item id='content' href='index.html' media-type='application/xhtml+xml'/>"
  Print #archivoOPF, "</manifest>"
  Print #archivoOPF, "<spine>"
  Print #archivoOPF, "    <itemref idref='content'/>"
  Print #archivoOPF, "</spine>"
  Print #archivoOPF, "</package>"

  Close archivoOPF

  ' Generar el EPUB con metadatos
  FMain.TerminalView1.Input("ebook-convert " & rutaEPUB1 & "content.opf " & rutaEPUB1 & "epub1-" & BaseName & ".epub" & " --title " & Quote$(BaseName) & " --language es --cover " & rutaEPUB1 & "cover.png --toc-threshold=1" & "\n")
  Wait 0.2

  ' Limpieza de archivos temporales
  FMain.TerminalView1.Input("rm -rf " & rutaEPUB1 & "index.html" & "\n")
  FMain.TerminalView1.Input("rm -rf " & rutaEPUB1 & "content.opf" & "\n")
  FMain.TerminalView1.Input("rm -rf " & rutaEPUB1 & "*.png" & "\n")
  Wait 0.2
  FMain.DirViewRuta.Reload
  FMain.FileView1.Reload

End

Public Sub salidaEPUBhtml()

  FMain.DirViewRuta.Refresh
  FMain.FileView1.Refresh

  ' obtenemos la exportación de los archivos bib, glo, metadatos y separata
  FMain.TabPanel1.Index = 0
  FMain.TabPanel6.Index = 0
  Mod_Exportar.Exportar2BibTeX(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2Glosario(FMain.TextBox1.Text)
  Mod_Exportar.Export2MetaEPUB(FMain.TextBox1.Text)
  Wait 0.2

  ' borramos el epub existente
  FMain.TerminalView1.Input("rm -rf epub2" & "\n")
  Wait 0.2

  ' copiamos las tipografias para el epub
  If Not File.RealPath(File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-Regular.woff2") Then
    Copy "./IBMPlexSans-Regular.woff2" To File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-Regular.woff2"
  End If
  Wait 0.1
  If Not File.RealPath(File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-Italic.woff2") Then
    Copy "./IBMPlexSans-Italic.woff2" To File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-Italic.woff2"
  End If
  Wait 0.1
  If Not File.RealPath(File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-SemiBold.woff2") Then
    Copy "./IBMPlexSans-SemiBold.woff2" To File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-SemiBold.woff2"
  End If
  Wait 0.1
  If Not File.RealPath(File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-SemiBoldItalic.woff2") Then
    Copy "./IBMPlexSans-SemiBoldItalic.woff2" To File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-SemiBoldItalic.woff2"
  End If
  Wait 0.1
  If Not File.RealPath(File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-Regular.woff") Then
    Copy "./IBMPlexSans-Regular.woff" To File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-Regular.woff"
  End If
  Wait 0.1
  If Not File.RealPath(File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-Italic.woff") Then
    Copy "./IBMPlexSans-Italic.woff" To File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-Italic.woff"
  End If
  Wait 0.1
  If Not File.RealPath(File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-SemiBold.woff") Then
    Copy "./IBMPlexSans-SemiBold.woff" To File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-SemiBold.woff"
  End If
  Wait 0.1
  If Not File.RealPath(File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-SemiBoldItalic.woff") Then
    Copy "./IBMPlexSans-SemiBoldItalic.woff" To File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-SemiBoldItalic.woff"
  End If
  Wait 0.1
  If Not File.RealPath(File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-Regular.ttf") Then
    Copy "./IBMPlexSans-Regular.ttf" To File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-Regular.ttf"
  End If
  Wait 0.1
  If Not File.RealPath(File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-Italic.ttf") Then
    Copy "./IBMPlexSans-Italic.ttf" To File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-Italic.ttf"
  End If
  Wait 0.1
  If Not File.RealPath(File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-SemiBold.ttf") Then
    Copy "./IBMPlexSans-SemiBold.ttf" To File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-SemiBold.ttf"
  End If
  Wait 0.1
  If Not File.RealPath(File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-SemiBoldItalic.ttf") Then
    Copy "./IBMPlexSans-SemiBoldItalic.ttf" To File.Dir(FMain.TextBox1.Text) & "/IBMPlexSans-SemiBoldItalic.ttf"
  End If
  Wait 0.1

  Dim condicional As String = "\\\\HTMLEPUBtrue"
  FMain.TerminalView1.Input("echo " & condicional & " >> " & rutaFILES & "/book-epub2.tex" & "\n")

  Dim newFile As String = "epub2-" & BaseName & ".tex"
  FMain.TerminalView1.Input("cat " & rutaFILES & "/book-epub2.tex " & File.Name(FMain.TextBox1.Text) & " > " & newFile & "\n")
  Wait 0.2

  Dim limpiarCondicional As String
  limpiarCondicional = "sed -i '/\\\\HTMLEPUBtrue/d' " & rutaFILES & "/book-epub2.tex" & "\n"
  FMain.TerminalView1.Input(limpiarCondicional)
  Wait 0.2

  FMain.TerminalView1.Input("cat " & rutaFILES & "/configEPUB.cfg" & " " & rutaFILES & "/gbTeXmeta-" & BaseName & ".tex" & " > " & rutaFILES & "/config.cfg" & "\n")
  Wait 0.2

  FMain.TerminalView1.Input("tex4ebook -l -f epub -c " & rutaFILES & "/config.cfg -e " & rutaFILES & "/build.lua -a debug " & newFile & " " & "\"tidy,shell-escape\"" & "\n")
  Wait 0.2

  FMain.TerminalView1.Input("mv epub2-" & BaseName & "-epub" & " " & "epub2" & "\n")
  Wait 0.2
  Mod_Funciones.Borrar_Aux
  FMain.DirViewRuta.Reload
  FMain.FileView1.Reload

End
