' Gambas module file

Public Conn As New Connection ' para acceder desde otros formularios

Public Function conectar() As Connection

  Dim conector As New Connection

  conector.Type = "sqlite3"
  conector.Host = User.Home & "/Dropbox/gbBaseDatos"
  conector.Name = "db_tex.sqlite"
  conector.Open()
  Return conector
  ' Configurar el modo de journal a DELETE para evitar los archivos .wal y .shm
  conector.Exec("PRAGMA journal_mode=DELETE;")

  If Error Then
    conector = Null
    Message.Error("Error al conectar con la base de datos. Asegúrese de que el archivo con la base de datos se encuentre disponible. La misma debe encontrarse en " & User.Home &/ ".gbtexpublisher")
  Endif

End

Public Sub desconectar(ByRef conector As Connection)

  conector.Close()
  conector = Null

End
