' Gambas module file

Private BaseName As String = File.BaseName(FMain.TextBox1.Text)
Private rutaFILES As String = File.Dir(FMain.TextBox1.Text) & "/files"

Public Sub salidaHTML5()

  ' obtenemos la exportación de los archivos bib, glo, metadatos y separata
  FMain.TabPanel1.Index = 0
  FMain.TabPanel6.Index = 0
  Mod_Exportar.ExportToSeparata(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2BibTeX(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2Glosario(FMain.TextBox1.Text)
  Mod_Exportar.Exportar2MetadatosPDF(FMain.TextBox1.Text)
  Wait 0.2

  Mod_Funciones.Borrar_Aux
  Wait 0.2

  If Not Exist(File.Dir(FMain.TextBox1.Text) & "/html") Then
    Mkdir File.Dir(FMain.TextBox1.Text) & "/html"
  End If

  Dim condicional As String = "\\\\HTMLtrue"
  FMain.TerminalView1.Input("echo " & condicional & " >> " & rutaFILES & "/book-html1.tex" & "\n")

  Dim newFile As String = "html1-" & BaseName & ".tex"
  FMain.TerminalView1.Input("cat " & rutaFILES & "/book-html1.tex " & File.Name(FMain.TextBox1.Text) & " > " & newFile & "\n")
  Wait 0.2

  Dim limpiarCondicional As String
  limpiarCondicional = "sed -i '/\\\\HTMLtrue/d' " & rutaFILES & "/book-html1.tex" & "\n"
  FMain.TerminalView1.Input(limpiarCondicional)

  Dim compilarlwarp As String
  compilarlwarp = "lwarpmk html " & newFile & "\n"
  FMain.TerminalView1.Input(compilarlwarp)
  Wait 0.2

  '
  ' eliminamos los archivos auxiliares
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/files/gbTeXglo-" & File.BaseName(FMain.TextBox1.Text) & ".tex" & "\n")
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/files/gbTeXbib-" & File.BaseName(FMain.TextBox1.Text) & ".bib" & "\n")
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/files/gbTeXmeta-" & File.BaseName(FMain.TextBox1.Text) & ".tex" & "\n")
  FMain.TerminalView1.Input("rm -rf " & File.Dir(FMain.TextBox1.Text) & "/files/gbTeXseparata-" & File.BaseName(FMain.TextBox1.Text) & ".tex" & "\n")
  Wait 0.2

  ' borramos los archivos auxiliares
  Mod_Funciones.Borrar_Aux

End
