' Gambas module file

' Private Name As String = File.Name(FMain.TextBox1.Text)
' Private BaseName As String = File.BaseName(FMain.TextBox1.Text)
' Private rutaBase As String = File.Dir(FMain.TextBox1.Text)

Public Sub CopiarArchivosRevista(rutaTexto As String)

  If Not Exist(File.Dir(rutaTexto) & "/media") Then
    Mkdir File.Dir(rutaTexto) & "/media"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/config") Then
    Mkdir File.Dir(rutaTexto) & "/config"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/art01") Then
    Mkdir File.Dir(rutaTexto) & "/art01"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/tapa") Then
    Mkdir File.Dir(rutaTexto) & "/tapa"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/readme.md") Then
    Copy "./readme.md" To File.Dir(rutaTexto) & "/readme.md"
  End If
  If Not Exist(File.Dir(rutaTexto) & "/LICENSE") Then
    Copy "./LICENSE2" To File.Dir(rutaTexto) & "/LICENSE"
  End If

End
