' Gambas module file

' Private hFile As File
' Public pSettings As Settings
' Public Matrix As New String[]
' Public ShortMatrix As New String[]
' Public sSlotName As String
' Public Const iLastNumber As Integer = 20

' Public Sub Init()
'
'   Dim sSettingsPath, sDirName, sSettingsFileName As String
'
'   sSlotName = "FileList"
'   sDirName = "LastFiles"
'   sSettingsPath = User.Home & "/.gbtexpublisher/" & sDirName
'   sSettingsFileName = "lastfiles.conf"
'
'   If Not Exist(sSettingsPath) Then
'     Mkdir sSettingsPath
'   Endif
'   If Not Exist(sSettingsPath &/ sSettingsFileName) Then
'     hFile = Open (sSettingsPath &/ sSettingsFileName) For Create
'     hFile.Close
'   Endif
'   ' Un objeto de configuración ve la luz en la memoria...
'   pSettings = New Settings(sSettingsPath &/ sSettingsFileName, "Listado")
'
' End

' Public Sub GetLastListFromSettings()
'
'   Dim iCount As Integer
'
'   pSettings.Reload() ' optional
'   Matrix.Clear
'   ShortMatrix.Clear
'   iCount = 0
'
'   While pSettings[sSlotName & "/File-" & Str(iCount)] <> Null
'     If Exist(pSettings[sSlotName & "/File-" & Str(iCount)]) Then '¿Existe este archivo en el sistema (aún)?
'       Matrix.Add(pSettings[sSlotName & "/File-" & Str(iCount)]) '...luego guardar la ruta del archivo en la matriz
'       ShortMatrix.Add(File.RealPath(pSettings[sSlotName & "/File-" & Str(iCount)])) '...y guardar el nombre del archivo en la matriz.
'     End If
'     Inc icount
'   Wend ' <> NULL
'
' End

' Public Sub SetLastListToSettings()
'
'   Dim iCount As Integer
'
'   pSettings.Clear
'   For iCount = 0 To Matrix.Max
'     pSettings[sSlotName & "/File-" & Str(iCount)] = Matrix[iCount]
'     'Se generarán como máximo 10 pares de clave-valor bajo el slot "LastFiles".
'   Next ' iCount
'   pSettings.Save 'Actualizando el archivo de configuración 'lastfiles.conf'.
'
' End
