# Configuración básica para GitHub Pages con tema Jekyll

# Nombre y descripción del sitio
title: gbTeXpublisher
description: Una solución potente y elegante desarrollada con Gambas para asistir al flujo de producción editorial

# temas oficiales:
# theme: jekyll-theme-cayman
remote_theme: pmarsceill/just-the-docs
# remote_theme: pages-themes/minimal
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/midnight

# Configuración de plugins
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-relative-links
  - jekyll-seo-tag

sass:
  style: compressed
  
# Permitir enlaces relativos en Markdown
relative_links:
  enabled: true
  collections: true

# Incluir estos archivos en el sitio
include:
  - index.md
  - cv.md
  - downloads.md

# Configuración de SEO
author: Alberto Moyano
social:
  name: Alberto Moyano
  links:
    - https://github.com/albertomoyano
    - https://www.linkedin.com/in/edicion-cientifica/

# Configuración de navegación
header_pages:
  - index.md
  - cv.md
  - downloads.md

# Configuración de Google Analytics (opcional)
# google_analytics: UA-XXXXXXXX-X

# Carpetas a ignorar
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
