# Configuración básica para GitHub Pages con tema Jekyll

# Nombre y descripción del sitio
title: gbTeXpublisher
description: Una solución potente y elegante desarrollada con Gambas para asistir al flujo de producción editorial

# Configuración del tema
# theme: jekyll-theme-cayman
remote_theme: pmarsceill/just-the-docs

# Configuración de plugins
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

# Permitir enlaces relativos en Markdown
relative_links:
  enabled: true
  collections: true

# Incluir estos archivos en el sitio
include:
  - index.md
  - cv.md
  - downloads.md

# Configuración de SEO
author: Alberto Moyano
social:
  name: Alberto Moyano
  links:
    - https://github.com/albertomoyano
    - https://www.linkedin.com/in/edicion-cientifica/

# Configuración de navegación
header_pages:
  - index.md
  - cv.md
  - downloads.md

# Incluye tu CSS
head_scripts:
  - /assets/css/custom.scss

# Configuración de Google Analytics (opcional)
# google_analytics: UA-XXXXXXXX-X

# Carpetas a ignorar
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
