name: DEB Package Deployment

on:
  push:
    paths:
      - 'ubuntu/paquetes/*.deb'

jobs:
  release-deb:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get DEB info
      id: deb-info
      run: |
        DEB_FILE=$(ls ubuntu/paquetes/*.deb | head -n 1)
        echo "name=$(basename "$DEB_FILE")" >> $GITHUB_OUTPUT
        echo "path=$DEB_FILE" >> $GITHUB_OUTPUT
        echo "version=$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.descargarDEB }}
      with:
        files: ${{ steps.deb-info.outputs.path }}
        tag_name: "deb-${{ steps.deb-info.outputs.version }}"
        name: "DEB Package ${{ steps.deb-info.outputs.version }}"
        body: "Package deployed automatically"

    - name: Create Deployment Record
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.repos.createDeployment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.ref,
            description: 'DEB Package Release',
            environment: 'deb-packages',
            auto_merge: false,
            required_contexts: []
          })